Feature/builder pickup to 1.11
ldtteam/minecolonies pull request #1000
Opened 2017-05-15 19:09 UTC by Raycoms

# Changes proposed in this pull request:
- Analog to 1.10 pr

Review please

2017-05-15 19:15 UTC, MinecoloniesSonar commented
SonarQube analysis reported 49 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 2 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L60](https://github.com/Minecolonies/minecolonies/blob/9107b39e9865bead0b26291e32e0c24ed637f808/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L60): class "AbstractEntityAIStructure" has 37 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L769](https://github.com/Minecolonies/minecolonies/blob/9107b39e9865bead0b26291e32e0c24ed637f808/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L769): Refactor this method to reduce its Cognitive Complexity from 32 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L48](https://github.com/Minecolonies/minecolonies/blob/9107b39e9865bead0b26291e32e0c24ed637f808/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L48): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 31 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L185](https://github.com/Minecolonies/minecolonies/blob/9107b39e9865bead0b26291e32e0c24ed637f808/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L185): The Cyclomatic Complexity of this method "requestMaterials" is 17 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L268](https://github.com/Minecolonies/minecolonies/blob/9107b39e9865bead0b26291e32e0c24ed637f808/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L268): Refactor this method to reduce its Cognitive Complexity from 21 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [Structure.java#L65](https://github.com/Minecolonies/minecolonies/blob/9107b39e9865bead0b26291e32e0c24ed637f808/src/main/java/com/minecolonies/coremod/entity/ai/util/Structure.java#L65): Reduce this class from 54 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [Structure.java#L165](https://github.com/Minecolonies/minecolonies/blob/9107b39e9865bead0b26291e32e0c24ed637f808/src/main/java/com/minecolonies/coremod/entity/ai/util/Structure.java#L165): Remove this unused private "structureBlockEqualsWorldBlock" method. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/9107b39e9865bead0b26291e32e0c24ed637f808/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/9107b39e9865bead0b26291e32e0c24ed637f808/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/9107b39e9865bead0b26291e32e0c24ed637f808/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-15 19:37 UTC, xavierh commented
Seems to be a lot of duplicated code between LumberJack and this (and maybe the Guard as well)
Could we not make this more generic and reusable ?

2017-05-15 19:43 UTC, Raycoms commented
I actually copied all the lumberjack code in the AbstractEntityAIInteract
to reuse it.
But true, we should be even able to get some of the guard code there as
well.

2017-05-15 16:37 GMT-03:00 xavierh <notifications@github.com>:

> Seems to be a lot of duplicated code between LumberJack and this (and
> maybe the Guard as well)
> Could we not make this more generic and reusable ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Minecolonies/minecolonies/pull/1000#issuecomment-301581001>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGI9y90fhu9C4BpW98MsBushB0vWZYnkks5r6KmFgaJpZM4Nbjr2>
> .
>

2017-05-15 20:00 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
>  import org.jetbrains.annotations.Nullable;
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Remove this unused import 'org.jetbrains.annotations.Nullable'. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

2017-05-15 20:00 UTC, MinecoloniesSonar commented
SonarQube analysis reported 50 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 41 minor
* ![INFO][INFO] 2 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L60](https://github.com/Minecolonies/minecolonies/blob/f48276bb0f3fb72693f5ff08d128dda0fc73534d/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L60): class "AbstractEntityAIStructure" has 37 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L769](https://github.com/Minecolonies/minecolonies/blob/f48276bb0f3fb72693f5ff08d128dda0fc73534d/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L769): Refactor this method to reduce its Cognitive Complexity from 32 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L48](https://github.com/Minecolonies/minecolonies/blob/f48276bb0f3fb72693f5ff08d128dda0fc73534d/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L48): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 31 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L185](https://github.com/Minecolonies/minecolonies/blob/f48276bb0f3fb72693f5ff08d128dda0fc73534d/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L185): The Cyclomatic Complexity of this method "requestMaterials" is 17 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L268](https://github.com/Minecolonies/minecolonies/blob/f48276bb0f3fb72693f5ff08d128dda0fc73534d/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L268): Refactor this method to reduce its Cognitive Complexity from 21 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [Structure.java#L65](https://github.com/Minecolonies/minecolonies/blob/f48276bb0f3fb72693f5ff08d128dda0fc73534d/src/main/java/com/minecolonies/coremod/entity/ai/util/Structure.java#L65): Reduce this class from 54 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [Structure.java#L165](https://github.com/Minecolonies/minecolonies/blob/f48276bb0f3fb72693f5ff08d128dda0fc73534d/src/main/java/com/minecolonies/coremod/entity/ai/util/Structure.java#L165): Remove this unused private "structureBlockEqualsWorldBlock" method. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/f48276bb0f3fb72693f5ff08d128dda0fc73534d/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/f48276bb0f3fb72693f5ff08d128dda0fc73534d/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/f48276bb0f3fb72693f5ff08d128dda0fc73534d/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-15 20:07 UTC, MinecoloniesSonar commented
SonarQube analysis reported 49 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 2 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L60](https://github.com/Minecolonies/minecolonies/blob/2fed832f6ecc333a201fe7ea3913858106379f8d/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L60): class "AbstractEntityAIStructure" has 37 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L769](https://github.com/Minecolonies/minecolonies/blob/2fed832f6ecc333a201fe7ea3913858106379f8d/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L769): Refactor this method to reduce its Cognitive Complexity from 32 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L48](https://github.com/Minecolonies/minecolonies/blob/2fed832f6ecc333a201fe7ea3913858106379f8d/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L48): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 31 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L185](https://github.com/Minecolonies/minecolonies/blob/2fed832f6ecc333a201fe7ea3913858106379f8d/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L185): The Cyclomatic Complexity of this method "requestMaterials" is 17 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L268](https://github.com/Minecolonies/minecolonies/blob/2fed832f6ecc333a201fe7ea3913858106379f8d/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L268): Refactor this method to reduce its Cognitive Complexity from 21 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [Structure.java#L65](https://github.com/Minecolonies/minecolonies/blob/2fed832f6ecc333a201fe7ea3913858106379f8d/src/main/java/com/minecolonies/coremod/entity/ai/util/Structure.java#L65): Reduce this class from 54 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [Structure.java#L165](https://github.com/Minecolonies/minecolonies/blob/2fed832f6ecc333a201fe7ea3913858106379f8d/src/main/java/com/minecolonies/coremod/entity/ai/util/Structure.java#L165): Remove this unused private "structureBlockEqualsWorldBlock" method. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/2fed832f6ecc333a201fe7ea3913858106379f8d/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/2fed832f6ecc333a201fe7ea3913858106379f8d/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/2fed832f6ecc333a201fe7ea3913858106379f8d/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-15 20:43 UTC, xavierh requested changes
Some java doc need to be changed

2017-05-15 20:43 UTC, xavierh commented on src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIInteract.java
> +     * Number of ticks the lumberjack is standing still.
Lumberjack ?

2017-05-15 20:43 UTC, xavierh commented on src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIInteract.java
> +     * Horizontal range in which the lumberjack picks up items.
worker

2017-05-15 20:43 UTC, xavierh commented on src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIInteract.java
> +     * Vertical range in which the lumberjack picks up items.
worker

2017-05-15 20:43 UTC, xavierh commented on src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIInteract.java
> +     * to check if the lumberjack is still walking.
worker

2017-05-15 20:43 UTC, xavierh commented on src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIInteract.java
> +     * Positions of all items that have to be collected.
If this is the items to be gathered, both the description and the name should mention it. Unless it was an AI solely to to the gathering

2017-05-15 20:43 UTC, xavierh commented on src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIInteract.java
> +    public void fillItemsList()
same here
javadoc too

2017-05-15 20:43 UTC, xavierh commented on src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIInteract.java
> +     * Search for all items around the Lumberjack.
worker

2017-05-15 20:43 UTC, xavierh commented on src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIInteract.java
> +    public List<BlockPos> getItems()
I find the name too generic

2017-05-15 21:41 UTC, MinecoloniesSonar commented
SonarQube analysis reported 49 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 2 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L60](https://github.com/Minecolonies/minecolonies/blob/d753096fdb78d077003d8b8e518f4afe3ab17829/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L60): class "AbstractEntityAIStructure" has 37 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L769](https://github.com/Minecolonies/minecolonies/blob/d753096fdb78d077003d8b8e518f4afe3ab17829/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L769): Refactor this method to reduce its Cognitive Complexity from 32 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L48](https://github.com/Minecolonies/minecolonies/blob/d753096fdb78d077003d8b8e518f4afe3ab17829/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L48): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 31 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L185](https://github.com/Minecolonies/minecolonies/blob/d753096fdb78d077003d8b8e518f4afe3ab17829/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L185): The Cyclomatic Complexity of this method "requestMaterials" is 17 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L268](https://github.com/Minecolonies/minecolonies/blob/d753096fdb78d077003d8b8e518f4afe3ab17829/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L268): Refactor this method to reduce its Cognitive Complexity from 21 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [Structure.java#L65](https://github.com/Minecolonies/minecolonies/blob/d753096fdb78d077003d8b8e518f4afe3ab17829/src/main/java/com/minecolonies/coremod/entity/ai/util/Structure.java#L65): Reduce this class from 54 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [Structure.java#L165](https://github.com/Minecolonies/minecolonies/blob/d753096fdb78d077003d8b8e518f4afe3ab17829/src/main/java/com/minecolonies/coremod/entity/ai/util/Structure.java#L165): Remove this unused private "structureBlockEqualsWorldBlock" method. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/d753096fdb78d077003d8b8e518f4afe3ab17829/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/d753096fdb78d077003d8b8e518f4afe3ab17829/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/d753096fdb78d077003d8b8e518f4afe3ab17829/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-15 22:30 UTC, xavierh approved these changes

2017-05-16 07:26 UTC, marvin-bitterlich requested changes
we could reduce this a bit :stuck_out_tongue_winking_eye:

2017-05-16 07:26 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java
> +        return world.getEntitiesWithinAABB(EntityItem.class, boundingBox)
why duplicate this? Can we abstract that?

2017-05-16 12:20 UTC, MinecoloniesSonar commented
SonarQube analysis reported 49 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 2 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L58](https://github.com/Minecolonies/minecolonies/blob/772960e6b397ba8f9cdd1dc43441348f3dadfbbc/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L58): class "AbstractEntityAIStructure" has 37 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L764](https://github.com/Minecolonies/minecolonies/blob/772960e6b397ba8f9cdd1dc43441348f3dadfbbc/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L764): Refactor this method to reduce its Cognitive Complexity from 32 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L48](https://github.com/Minecolonies/minecolonies/blob/772960e6b397ba8f9cdd1dc43441348f3dadfbbc/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L48): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 31 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L185](https://github.com/Minecolonies/minecolonies/blob/772960e6b397ba8f9cdd1dc43441348f3dadfbbc/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L185): The Cyclomatic Complexity of this method "requestMaterials" is 17 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L268](https://github.com/Minecolonies/minecolonies/blob/772960e6b397ba8f9cdd1dc43441348f3dadfbbc/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L268): Refactor this method to reduce its Cognitive Complexity from 21 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [Structure.java#L65](https://github.com/Minecolonies/minecolonies/blob/772960e6b397ba8f9cdd1dc43441348f3dadfbbc/src/main/java/com/minecolonies/coremod/entity/ai/util/Structure.java#L65): Reduce this class from 54 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [Structure.java#L165](https://github.com/Minecolonies/minecolonies/blob/772960e6b397ba8f9cdd1dc43441348f3dadfbbc/src/main/java/com/minecolonies/coremod/entity/ai/util/Structure.java#L165): Remove this unused private "structureBlockEqualsWorldBlock" method. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/772960e6b397ba8f9cdd1dc43441348f3dadfbbc/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/772960e6b397ba8f9cdd1dc43441348f3dadfbbc/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/772960e6b397ba8f9cdd1dc43441348f3dadfbbc/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-16 13:46 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java
> +        return world.getEntitiesWithinAABB(EntityItem.class, boundingBox)
done

2017-05-17 04:42 UTC, marvin-bitterlich approved these changes

2017-05-17 04:42 UTC, merged