Food related forge:tags work
ldtteam/minecolonies pull request #10045
Opened 2024-07-16 12:57 UTC by supernova0102

# Changes proposed in this pull request:
- Add Crops, vegetables, dough, grain, etc, some of food related tags
- Will be able to use Minecolonies' crops for making food of other mods
- Still not able to make Minecolonies' food using other mods' crops

[O] Yes I tested this before submitting it.
[ ] I also did a multiplayer test. <= not need maybe?

Review please

2024-07-16 12:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ldtteam/minecolonies?pullRequest=10045) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ldtteam/minecolonies?pullRequest=10045) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ldtteam/minecolonies?pullRequest=10045) it.</sub>

2024-07-16 12:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ldtteam/minecolonies?pullRequest=10045) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ldtteam/minecolonies?pullRequest=10045) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ldtteam/minecolonies?pullRequest=10045) it.</sub>

2024-07-16 13:02 UTC, uecasm commented
If you want to put tags into `datagen`, you need the associated datagen code as well.  Otherwise the tags should be in `main`.

2024-07-16 13:16 UTC, supernova0102 commented
> If you want to put tags into `datagen`, you need the associated datagen code as well. Otherwise the tags should be in `main`.

Got it
fix it will soon
Thank you for your comment

2024-07-16 13:17 UTC, supernova0102 commented
will fix

> If you want to put tags into `datagen`, you need the associated datagen code as well. Otherwise the tags should be in `main`.

2024-07-16 13:19 UTC, Thodor12 commented
You don't have to close a pull request, just commit the new changes where the files are supposed to be and you're good

2024-07-16 13:23 UTC, supernova0102 commented
Commited
Moved tag file to `main`

2024-07-21 11:00 UTC, Raycoms approved these changes

2024-07-21 13:12 UTC, someaddons commented
Looks a bit odd, why are all those tags under forge loot modifiers?

2024-07-21 13:16 UTC, Raycoms requested changes

2024-07-21 13:16 UTC, Raycoms commented on src/main/resources/data/forge/loot_modifiers/tags/items/grain/chickpea.json
Loot modifiers seems like the wrong folder for this

2024-08-12 13:59 UTC, supernova0102 commented on src/main/resources/data/forge/loot_modifiers/tags/items/grain/chickpea.json
solved

2024-08-12 14:07 UTC, someaddons commented on src/main/resources/data/forge/tags/items/crops.json
> +        "#forge:crops/tomato"
we shouldnt add them to the crops tag, because they're not behaving like normal crops which other mods would expect

2024-10-30 14:48 UTC, Raycoms commented
Tags already added now

2024-10-30 14:48 UTC, closed without merging