Buildtool descriptions
ldtteam/minecolonies pull request #10089
Opened 2024-08-02 17:32 UTC by someaddons

Closes #
Closes #
Closes #

# Changes proposed in this pull request:
- Reworked building desc in buildtool
- Added raider highlight when only 15% are left
- Changed all wordings from colonist to citizen

[ x] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please

2024-08-02 17:34 UTC, Raycoms commented on src/main/resources/assets/minecolonies/lang/manual_en_us.json
> +  "com.minecolonies.building.simplequarry.desc": "Small quarrying area for a quarrier, used for mining and extracting stones",
quarrying area sounds weird

2024-08-02 17:37 UTC, Raycoms commented on src/main/resources/assets/minecolonies/lang/manual_en_us.json
> +  "com.minecolonies.building.kitchen.desc": "Prepares and cooks a range of food items for the colony",
I think dishes instead of food items

2024-08-02 17:37 UTC, Raycoms commented on src/main/resources/assets/minecolonies/lang/manual_en_us.json
> +  "com.minecolonies.building.library.desc": "Educates grown citizens, enhancing their intelligence and knowledge",
The library educates?

2024-09-05 13:23 UTC, Imrielle requested changes
Suggested changes left in comments, otherwise - looks fine.

2024-09-05 13:23 UTC, Imrielle commented on src/main/resources/assets/minecolonies/lang/manual_en_us.json
> +  "com.minecolonies.building.chickenherder.desc": "Handles chicken to produce feathers and eggs",
Handles chickens to produce feathers and eggs

2024-09-05 13:23 UTC, Imrielle commented on src/main/resources/assets/minecolonies/lang/manual_en_us.json
>    "com.minecolonies.coremod.structures.nocustomhuts": "The builder never heard of this blueprint for this building. Are you sure you handled this correctly?",
The builder has never heard of this blueprint for this building. Are you sure you handled this correctly?

2024-09-15 13:10 UTC, merged