Port to 1.11 (waypoints, colony border, sounds, warehouse restriction)
ldtteam/minecolonies pull request #1032
Opened 2017-05-21 18:07 UTC by Raycoms

# Changes proposed in this pull request:
- Port to 1.11 of the above-mentioned past prs. 

That should be all which isn't up to data in 1.11

Review please

2017-05-21 19:22 UTC, Kostronor commented
LGTM it is just the port

2017-05-21 20:02 UTC, marvin-bitterlich requested changes
well, javadoc errors xD

2017-05-21 20:24 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/colony/ColonyView.java
>      private double overallHappiness = 5;
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Assign this magic number 5 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

2017-05-21 20:24 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/sounds/ModSoundEvents.java
> +    public static final List<AbstractWorkerSounds> handlers = new ArrayList<>();
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Make this member "protected". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2386)

2017-05-21 20:24 UTC, MinecoloniesSonar commented
SonarQube analysis reported 104 issues
* ![MAJOR][MAJOR] 39 major
* ![MINOR][MINOR] 51 minor
* ![INFO][INFO] 14 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/078a8bcba73afb44eaa8617e537ab83e202c0c29/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.221 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/078a8bcba73afb44eaa8617e537ab83e202c0c29/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 43 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/078a8bcba73afb44eaa8617e537ab83e202c0c29/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): class "Colony" has 83 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L178](https://github.com/Minecolonies/minecolonies/blob/078a8bcba73afb44eaa8617e537ab83e202c0c29/src/main/java/com/minecolonies/coremod/colony/Colony.java#L178): Assign this magic number 5 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L558](https://github.com/Minecolonies/minecolonies/blob/078a8bcba73afb44eaa8617e537ab83e202c0c29/src/main/java/com/minecolonies/coremod/colony/Colony.java#L558): Reduce the number of returns of this method 11, down to the maximum allowed 6. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1022](https://github.com/Minecolonies/minecolonies/blob/078a8bcba73afb44eaa8617e537ab83e202c0c29/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1022): Assign this magic number 20 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1023](https://github.com/Minecolonies/minecolonies/blob/078a8bcba73afb44eaa8617e537ab83e202c0c29/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1023): Assign this magic number 60 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1147](https://github.com/Minecolonies/minecolonies/blob/078a8bcba73afb44eaa8617e537ab83e202c0c29/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1147): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1149](https://github.com/Minecolonies/minecolonies/blob/078a8bcba73afb44eaa8617e537ab83e202c0c29/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1149): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1151](https://github.com/Minecolonies/minecolonies/blob/078a8bcba73afb44eaa8617e537ab83e202c0c29/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1151): Assign this magic number 128 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-21 20:59 UTC, xavierh commented
LGTM

2017-05-21 21:35 UTC, MinecoloniesSonar commented
SonarQube analysis reported 104 issues
* ![MAJOR][MAJOR] 39 major
* ![MINOR][MINOR] 51 minor
* ![INFO][INFO] 14 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/6047b683dd21a6c3e1544bb7ed58a61f5d78a0d2/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.221 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/6047b683dd21a6c3e1544bb7ed58a61f5d78a0d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 43 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/6047b683dd21a6c3e1544bb7ed58a61f5d78a0d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): class "Colony" has 83 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L178](https://github.com/Minecolonies/minecolonies/blob/6047b683dd21a6c3e1544bb7ed58a61f5d78a0d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L178): Assign this magic number 5 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L558](https://github.com/Minecolonies/minecolonies/blob/6047b683dd21a6c3e1544bb7ed58a61f5d78a0d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L558): Reduce the number of returns of this method 11, down to the maximum allowed 6. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1022](https://github.com/Minecolonies/minecolonies/blob/6047b683dd21a6c3e1544bb7ed58a61f5d78a0d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1022): Assign this magic number 20 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1023](https://github.com/Minecolonies/minecolonies/blob/6047b683dd21a6c3e1544bb7ed58a61f5d78a0d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1023): Assign this magic number 60 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1147](https://github.com/Minecolonies/minecolonies/blob/6047b683dd21a6c3e1544bb7ed58a61f5d78a0d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1147): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1149](https://github.com/Minecolonies/minecolonies/blob/6047b683dd21a6c3e1544bb7ed58a61f5d78a0d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1149): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1151](https://github.com/Minecolonies/minecolonies/blob/6047b683dd21a6c3e1544bb7ed58a61f5d78a0d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1151): Assign this magic number 128 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-22 07:58 UTC, marvin-bitterlich approved these changes

2017-05-22 07:58 UTC, merged