Sound fixes for block placing/breaking
ldtteam/minecolonies pull request #10423
Opened 2024-11-09 23:22 UTC by Sindarin27

This pull request makes slight adjustments to the sound effects created when citizens place or break blocks, to sound more in-line with the sound effects used in Vanilla.

# Changes proposed in this pull request
- When placing, hitting, or breaking a block, the same pitch and volume calculations are used as in Vanilla functions. 
   - In practice: block sounds are lowered in pitch to match Vanilla sounds.
- When a builder places a solid substitution block, use the sound effect of the block that is substituted instead of the sound of the solid substitution block itself. 
   - In practice: builders placing dirt blocks to fill an area now makes dirt placing sounds instead of wood placing sounds.
- When hitting a block but not yet breaking it, use the block's hit sound instead of the break sound. 
   - In practice: a builder digging up e.g. grass blocks now makes a lot less noise.

## Testing
- [x] Yes I tested this before submitting it.
- [x] I also did a multiplayer test.

Review please

2024-11-09 23:44 UTC, Raycoms requested changes
Hello, thank you for your PR, I just left a minor comment for now

2024-11-09 23:44 UTC, Raycoms commented on src/main/java/com/minecolonies/core/entity/ai/workers/util/BuildingStructureHandler.java
> +            if (state.getBlock() == com.ldtteam.structurize.blocks.ModBlocks.blockSolidSubstitution.get()) {
Please apply our formatting rules here

2024-11-10 14:05 UTC, Raycoms approved these changes

2024-11-10 21:12 UTC, someaddons approved these changes

2024-11-10 21:14 UTC, merged