Feature/lumberjack sapling selector
ldtteam/minecolonies pull request #1189
Opened 2017-06-16 01:42 UTC by Raycoms

Closes #1039 
Closes #763

# Changes proposed in this pull request:
- Lumberjack now has a list with saplings of trees the lumberjack is supposed to cut.
- Reworked the Itemstorage (should be better now, still needs to be improved slightly)
- Removed not existent farmer sound
- Fix Baker string

Review please

2017-06-16 01:46 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/entity/pathfinding/PathJobFindTree.java
> +import net.minecraft.item.ItemStack;
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Remove this unused import 'net.minecraft.item.ItemStack'. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

2017-06-16 01:46 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java
> +import net.minecraft.item.ItemStack;
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Remove this unused import 'net.minecraft.item.ItemStack'. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

2017-06-16 01:46 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/colony/buildings/BuildingLumberjack.java
>      public static class View extends AbstractBuildingWorker.View
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Reduce this class from 39 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)

2017-06-16 01:46 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java
> +    private static boolean hasEnoughLeavesAndIsSupposedToCut(@NotNull final IBlockAccess world, final BlockPos pos, final Map<ItemStorage, Boolean> treesToCut)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Refactor this method to reduce its Cognitive Complexity from 21 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

2017-06-16 01:46 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java
> +                if(variantNumber == stack.getItemStack().getMetadata())
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Merge this if statement with the enclosing one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1066)

2017-06-16 01:46 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/colony/buildings/BuildingBuilder.java
>              //ByteBufUtils.writeItemStack() is Buggy, serialize itemId and damage separately;
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') This block of commented-out lines of code should be removed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

2017-06-16 01:46 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/client/gui/WindowHutLumberjack.java
> +        saplingsList.setDataProvider(new ScrollingList.DataProvider()
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Reduce this anonymous class number of lines from 23 to at most 20, or make it a named class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)

2017-06-16 01:46 UTC, MinecoloniesSonar commented
SonarQube analysis reported 65 issues
* ![MAJOR][MAJOR] 24 major
* ![MINOR][MINOR] 38 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [BuildingFarmer.java#L520](https://github.com/Minecolonies/minecolonies/blob/fd550ce901e8b4e0af372a773991a0c4ca8b949c/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L520): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingMiner.java#L479](https://github.com/Minecolonies/minecolonies/blob/fd550ce901e8b4e0af372a773991a0c4ca8b949c/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingMiner.java#L479): Assign this magic number 3 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [BuildingMiner.java#L656](https://github.com/Minecolonies/minecolonies/blob/fd550ce901e8b4e0af372a773991a0c4ca8b949c/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingMiner.java#L656): Reduce this class from 39 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L39](https://github.com/Minecolonies/minecolonies/blob/fd550ce901e8b4e0af372a773991a0c4ca8b949c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L39): class "AbstractEntityAIBasic" has 56 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L204](https://github.com/Minecolonies/minecolonies/blob/fd550ce901e8b4e0af372a773991a0c4ca8b949c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L204): Either log or rethrow this exception. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L532](https://github.com/Minecolonies/minecolonies/blob/fd550ce901e8b4e0af372a773991a0c4ca8b949c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L532): Remove this unused private "requestWithoutSpam" method. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L983](https://github.com/Minecolonies/minecolonies/blob/fd550ce901e8b4e0af372a773991a0c4ca8b949c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L983): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1032](https://github.com/Minecolonies/minecolonies/blob/fd550ce901e8b4e0af372a773991a0c4ca8b949c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1032): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L51](https://github.com/Minecolonies/minecolonies/blob/fd550ce901e8b4e0af372a773991a0c4ca8b949c/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L51): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 31 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L176](https://github.com/Minecolonies/minecolonies/blob/fd550ce901e8b4e0af372a773991a0c4ca8b949c/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L176): The Cyclomatic Complexity of this method "requestMaterials" is 17 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-16 13:20 UTC, MinecoloniesSonar commented
SonarQube analysis reported 56 issues
* ![MAJOR][MAJOR] 19 major
* ![MINOR][MINOR] 34 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [BuildingFarmer.java#L520](https://github.com/Minecolonies/minecolonies/blob/fff10eb2b1593f14f89413492deacf198c8a4a8f/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L520): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingMiner.java#L479](https://github.com/Minecolonies/minecolonies/blob/fff10eb2b1593f14f89413492deacf198c8a4a8f/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingMiner.java#L479): Assign this magic number 3 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [BuildingMiner.java#L656](https://github.com/Minecolonies/minecolonies/blob/fff10eb2b1593f14f89413492deacf198c8a4a8f/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingMiner.java#L656): Reduce this class from 39 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L39](https://github.com/Minecolonies/minecolonies/blob/fff10eb2b1593f14f89413492deacf198c8a4a8f/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L39): class "AbstractEntityAIBasic" has 56 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L204](https://github.com/Minecolonies/minecolonies/blob/fff10eb2b1593f14f89413492deacf198c8a4a8f/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L204): Either log or rethrow this exception. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L532](https://github.com/Minecolonies/minecolonies/blob/fff10eb2b1593f14f89413492deacf198c8a4a8f/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L532): Remove this unused private "requestWithoutSpam" method. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L983](https://github.com/Minecolonies/minecolonies/blob/fff10eb2b1593f14f89413492deacf198c8a4a8f/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L983): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1032](https://github.com/Minecolonies/minecolonies/blob/fff10eb2b1593f14f89413492deacf198c8a4a8f/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1032): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [PathNavigate.java#L199](https://github.com/Minecolonies/minecolonies/blob/fff10eb2b1593f14f89413492deacf198c8a4a8f/src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java#L199): This method has 103 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS138)
1. ![MAJOR][MAJOR] [PathNavigate.java#L199](https://github.com/Minecolonies/minecolonies/blob/fff10eb2b1593f14f89413492deacf198c8a4a8f/src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java#L199): The Cyclomatic Complexity of this method "onUpdateNavigation" is 25 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-17 09:49 UTC, marchermans requested changes
Looks good. No Idea if the UI works, as i have not understood that System yet, but from a glance this Looks nicely implemented.

Remove the weird logging of lalala and we are good to go.

2017-06-17 09:49 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/colony/buildings/BuildingLumberjack.java
> +        Log.getLogger().info("Lalala");
Please remove this or put something usefull in here.

2017-06-17 13:59 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/colony/buildings/BuildingLumberjack.java
> +        Log.getLogger().info("Lalala");
I always forget those debug loggers I put there =D

2017-06-17 14:04 UTC, MinecoloniesSonar commented
SonarQube analysis reported 56 issues
* ![MAJOR][MAJOR] 19 major
* ![MINOR][MINOR] 34 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [BuildingFarmer.java#L520](https://github.com/Minecolonies/minecolonies/blob/0edd1ae318f4853b4e87da4eaa270ed4f74575b0/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L520): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingMiner.java#L479](https://github.com/Minecolonies/minecolonies/blob/0edd1ae318f4853b4e87da4eaa270ed4f74575b0/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingMiner.java#L479): Assign this magic number 3 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [BuildingMiner.java#L656](https://github.com/Minecolonies/minecolonies/blob/0edd1ae318f4853b4e87da4eaa270ed4f74575b0/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingMiner.java#L656): Reduce this class from 39 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L39](https://github.com/Minecolonies/minecolonies/blob/0edd1ae318f4853b4e87da4eaa270ed4f74575b0/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L39): class "AbstractEntityAIBasic" has 56 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L204](https://github.com/Minecolonies/minecolonies/blob/0edd1ae318f4853b4e87da4eaa270ed4f74575b0/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L204): Either log or rethrow this exception. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L532](https://github.com/Minecolonies/minecolonies/blob/0edd1ae318f4853b4e87da4eaa270ed4f74575b0/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L532): Remove this unused private "requestWithoutSpam" method. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L983](https://github.com/Minecolonies/minecolonies/blob/0edd1ae318f4853b4e87da4eaa270ed4f74575b0/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L983): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1032](https://github.com/Minecolonies/minecolonies/blob/0edd1ae318f4853b4e87da4eaa270ed4f74575b0/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1032): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [PathNavigate.java#L199](https://github.com/Minecolonies/minecolonies/blob/0edd1ae318f4853b4e87da4eaa270ed4f74575b0/src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java#L199): This method has 103 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS138)
1. ![MAJOR][MAJOR] [PathNavigate.java#L199](https://github.com/Minecolonies/minecolonies/blob/0edd1ae318f4853b4e87da4eaa270ed4f74575b0/src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java#L199): The Cyclomatic Complexity of this method "onUpdateNavigation" is 25 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-17 14:12 UTC, MinecoloniesSonar commented
SonarQube analysis reported 56 issues
* ![MAJOR][MAJOR] 19 major
* ![MINOR][MINOR] 34 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [BuildingFarmer.java#L520](https://github.com/Minecolonies/minecolonies/blob/4ba3b02c977dcbd0318f51223017c3bcc033282c/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L520): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingMiner.java#L479](https://github.com/Minecolonies/minecolonies/blob/4ba3b02c977dcbd0318f51223017c3bcc033282c/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingMiner.java#L479): Assign this magic number 3 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [BuildingMiner.java#L656](https://github.com/Minecolonies/minecolonies/blob/4ba3b02c977dcbd0318f51223017c3bcc033282c/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingMiner.java#L656): Reduce this class from 39 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L39](https://github.com/Minecolonies/minecolonies/blob/4ba3b02c977dcbd0318f51223017c3bcc033282c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L39): class "AbstractEntityAIBasic" has 56 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L204](https://github.com/Minecolonies/minecolonies/blob/4ba3b02c977dcbd0318f51223017c3bcc033282c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L204): Either log or rethrow this exception. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L532](https://github.com/Minecolonies/minecolonies/blob/4ba3b02c977dcbd0318f51223017c3bcc033282c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L532): Remove this unused private "requestWithoutSpam" method. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L983](https://github.com/Minecolonies/minecolonies/blob/4ba3b02c977dcbd0318f51223017c3bcc033282c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L983): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1032](https://github.com/Minecolonies/minecolonies/blob/4ba3b02c977dcbd0318f51223017c3bcc033282c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1032): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [PathNavigate.java#L199](https://github.com/Minecolonies/minecolonies/blob/4ba3b02c977dcbd0318f51223017c3bcc033282c/src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java#L199): This method has 103 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS138)
1. ![MAJOR][MAJOR] [PathNavigate.java#L199](https://github.com/Minecolonies/minecolonies/blob/4ba3b02c977dcbd0318f51223017c3bcc033282c/src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java#L199): The Cyclomatic Complexity of this method "onUpdateNavigation" is 25 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-17 15:58 UTC, marchermans approved these changes

2017-06-17 16:07 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/colony/buildings/BuildingLumberjack.java
>  public class BuildingLumberjack extends AbstractBuildingWorker
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Override the "equals" method in this class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2160)

2017-06-17 16:07 UTC, MinecoloniesSonar commented
SonarQube analysis reported 62 issues
* ![MAJOR][MAJOR] 19 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [BuildingFarmer.java#L520](https://github.com/Minecolonies/minecolonies/blob/cca5f6e8b934a00bab4cc7c92a87f9215bfbdf85/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L520): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingMiner.java#L479](https://github.com/Minecolonies/minecolonies/blob/cca5f6e8b934a00bab4cc7c92a87f9215bfbdf85/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingMiner.java#L479): Assign this magic number 3 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [BuildingMiner.java#L656](https://github.com/Minecolonies/minecolonies/blob/cca5f6e8b934a00bab4cc7c92a87f9215bfbdf85/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingMiner.java#L656): Reduce this class from 39 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L39](https://github.com/Minecolonies/minecolonies/blob/cca5f6e8b934a00bab4cc7c92a87f9215bfbdf85/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L39): class "AbstractEntityAIBasic" has 56 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L204](https://github.com/Minecolonies/minecolonies/blob/cca5f6e8b934a00bab4cc7c92a87f9215bfbdf85/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L204): Either log or rethrow this exception. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L532](https://github.com/Minecolonies/minecolonies/blob/cca5f6e8b934a00bab4cc7c92a87f9215bfbdf85/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L532): Remove this unused private "requestWithoutSpam" method. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L983](https://github.com/Minecolonies/minecolonies/blob/cca5f6e8b934a00bab4cc7c92a87f9215bfbdf85/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L983): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1032](https://github.com/Minecolonies/minecolonies/blob/cca5f6e8b934a00bab4cc7c92a87f9215bfbdf85/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1032): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [PathNavigate.java#L199](https://github.com/Minecolonies/minecolonies/blob/cca5f6e8b934a00bab4cc7c92a87f9215bfbdf85/src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java#L199): This method has 103 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS138)
1. ![MAJOR][MAJOR] [PathNavigate.java#L199](https://github.com/Minecolonies/minecolonies/blob/cca5f6e8b934a00bab4cc7c92a87f9215bfbdf85/src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java#L199): The Cyclomatic Complexity of this method "onUpdateNavigation" is 25 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-19 12:13 UTC, MinecoloniesSonar commented
SonarQube analysis reported 62 issues
* ![MAJOR][MAJOR] 19 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [BuildingFarmer.java#L520](https://github.com/Minecolonies/minecolonies/blob/818dbc1881b3491694bf404902f9d114045b5573/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L520): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingMiner.java#L479](https://github.com/Minecolonies/minecolonies/blob/818dbc1881b3491694bf404902f9d114045b5573/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingMiner.java#L479): Assign this magic number 3 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [BuildingMiner.java#L656](https://github.com/Minecolonies/minecolonies/blob/818dbc1881b3491694bf404902f9d114045b5573/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingMiner.java#L656): Reduce this class from 39 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L39](https://github.com/Minecolonies/minecolonies/blob/818dbc1881b3491694bf404902f9d114045b5573/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L39): class "AbstractEntityAIBasic" has 56 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L204](https://github.com/Minecolonies/minecolonies/blob/818dbc1881b3491694bf404902f9d114045b5573/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L204): Either log or rethrow this exception. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L532](https://github.com/Minecolonies/minecolonies/blob/818dbc1881b3491694bf404902f9d114045b5573/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L532): Remove this unused private "requestWithoutSpam" method. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L983](https://github.com/Minecolonies/minecolonies/blob/818dbc1881b3491694bf404902f9d114045b5573/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L983): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1032](https://github.com/Minecolonies/minecolonies/blob/818dbc1881b3491694bf404902f9d114045b5573/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1032): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [PathNavigate.java#L199](https://github.com/Minecolonies/minecolonies/blob/818dbc1881b3491694bf404902f9d114045b5573/src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java#L199): This method has 103 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS138)
1. ![MAJOR][MAJOR] [PathNavigate.java#L199](https://github.com/Minecolonies/minecolonies/blob/818dbc1881b3491694bf404902f9d114045b5573/src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java#L199): The Cyclomatic Complexity of this method "onUpdateNavigation" is 25 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-19 13:12 UTC, xavierh approved these changes

2017-06-19 13:16 UTC, MinecoloniesSonar commented
SonarQube analysis reported 62 issues
* ![MAJOR][MAJOR] 19 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [BuildingFarmer.java#L520](https://github.com/Minecolonies/minecolonies/blob/98a6eab3620f6e051ffe389dadeccc72c16599e3/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L520): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingMiner.java#L479](https://github.com/Minecolonies/minecolonies/blob/98a6eab3620f6e051ffe389dadeccc72c16599e3/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingMiner.java#L479): Assign this magic number 3 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [BuildingMiner.java#L656](https://github.com/Minecolonies/minecolonies/blob/98a6eab3620f6e051ffe389dadeccc72c16599e3/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingMiner.java#L656): Reduce this class from 39 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L39](https://github.com/Minecolonies/minecolonies/blob/98a6eab3620f6e051ffe389dadeccc72c16599e3/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L39): class "AbstractEntityAIBasic" has 56 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L204](https://github.com/Minecolonies/minecolonies/blob/98a6eab3620f6e051ffe389dadeccc72c16599e3/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L204): Either log or rethrow this exception. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L532](https://github.com/Minecolonies/minecolonies/blob/98a6eab3620f6e051ffe389dadeccc72c16599e3/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L532): Remove this unused private "requestWithoutSpam" method. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUnusedPrivateMethod)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L983](https://github.com/Minecolonies/minecolonies/blob/98a6eab3620f6e051ffe389dadeccc72c16599e3/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L983): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1032](https://github.com/Minecolonies/minecolonies/blob/98a6eab3620f6e051ffe389dadeccc72c16599e3/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1032): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MAJOR][MAJOR] [PathNavigate.java#L199](https://github.com/Minecolonies/minecolonies/blob/98a6eab3620f6e051ffe389dadeccc72c16599e3/src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java#L199): This method has 103 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS138)
1. ![MAJOR][MAJOR] [PathNavigate.java#L199](https://github.com/Minecolonies/minecolonies/blob/98a6eab3620f6e051ffe389dadeccc72c16599e3/src/main/java/com/minecolonies/coremod/entity/pathfinding/PathNavigate.java#L199): The Cyclomatic Complexity of this method "onUpdateNavigation" is 25 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-19 17:44 UTC, merged