Several small fixes
ldtteam/minecolonies pull request #1194
Opened 2017-06-16 19:29 UTC by Raycoms

Closes #1193 

# Changes proposed in this pull request:
- Fixes problems with several dman trying to deliver at the same time.
- Fixes problems with food not being delivered correctly
- Allows players to eat food in colonies and defend themselves against mobs

Review please

2017-06-16 19:33 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
> +        if(((AbstractBuilding) o).getID().equals(this.getID()))
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this if-then-else statement by a single return statement. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1126)

2017-06-16 19:33 UTC, MinecoloniesSonar commented
SonarQube analysis reported 66 issues
* ![MAJOR][MAJOR] 33 major
* ![MINOR][MINOR] 33 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 35 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): class "AbstractBuilding" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingBuilder". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L124](https://github.com/Minecolonies/minecolonies/blob/33b26dbd0973515ef665d3e7479d9b47bfb2816a/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L124): Remove this reference to "BuildingFarmer". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-16 20:42 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/colony/workorders/WorkOrderBuildDecoration.java
>      @SuppressWarnings("squid:S1172")
![INFO](https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO') Suppressing the 'squid:S1172' warning is not allowed [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1309)

2017-06-16 20:42 UTC, MinecoloniesSonar commented
SonarQube analysis reported 68 issues
* ![MAJOR][MAJOR] 33 major
* ![MINOR][MINOR] 32 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 35 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): class "AbstractBuilding" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingBuilder". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L124](https://github.com/Minecolonies/minecolonies/blob/539b141edb8dd17a06d386057fdac9b52c1098a8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L124): Remove this reference to "BuildingFarmer". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-16 20:56 UTC, MinecoloniesSonar commented
SonarQube analysis reported 69 issues
* ![MAJOR][MAJOR] 34 major
* ![MINOR][MINOR] 32 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 35 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): class "AbstractBuilding" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingBuilder". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L124](https://github.com/Minecolonies/minecolonies/blob/493eace03c0d622f1e030b5c8ded165b979ec373/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L124): Remove this reference to "BuildingFarmer". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-17 09:45 UTC, marchermans requested changes
Change the for-loop to a lamda and we are good to go.

2017-06-17 09:45 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
> +    public boolean equals(final Object o)
👍

2017-06-17 09:45 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
> +    public int hashCode()
👍

2017-06-17 09:45 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/colony/buildings/BuildingHome.java
> +        for(final CitizenData resident: residents)
This can simply be done by a lamda (with findFirst and filter)
Would make this Code footprint a lot smaller and the JVM can optimize it better.

2017-06-17 14:04 UTC, MinecoloniesSonar commented
SonarQube analysis reported 69 issues
* ![MAJOR][MAJOR] 34 major
* ![MINOR][MINOR] 32 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 35 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): class "AbstractBuilding" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingBuilder". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L124](https://github.com/Minecolonies/minecolonies/blob/f94aac7cfb20ad30e633a22ad068c7d511d877d4/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L124): Remove this reference to "BuildingFarmer". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-17 14:14 UTC, MinecoloniesSonar commented
SonarQube analysis reported 69 issues
* ![MAJOR][MAJOR] 34 major
* ![MINOR][MINOR] 32 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 35 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L43](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L43): class "AbstractBuilding" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L120](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L120): Remove this reference to "BuildingBaker". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L121](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L121): Remove this reference to "BuildingBlacksmith". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L122](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L122): Remove this reference to "BuildingBuilder". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L123](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L123): Remove this reference to "BuildingHome". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L124](https://github.com/Minecolonies/minecolonies/blob/6e576a5f0000bb1b670c8eca5e91a5e37b3cdca5/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L124): Remove this reference to "BuildingFarmer". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-17 15:11 UTC, Kostronor commented
LGTM

2017-06-17 15:57 UTC, marchermans approved these changes

2017-06-17 15:57 UTC, merged