GuideBook Done
ldtteam/minecolonies pull request #1208
Opened 2017-06-19 02:35 UTC by Asherslab

# Changes proposed in this pull request:
- Puts the Guide Book in the game (if mod is installed) 

Review please

2017-06-19 02:39 UTC, MinecoloniesSonar commented
SonarQube analysis reported 26 issues
* ![MINOR][MINOR] 26 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/b5d461e3fce3021af15051e052a3406516bc0e24/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/b5d461e3fce3021af15051e052a3406516bc0e24/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/b5d461e3fce3021af15051e052a3406516bc0e24/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/b5d461e3fce3021af15051e052a3406516bc0e24/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/b5d461e3fce3021af15051e052a3406516bc0e24/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/b5d461e3fce3021af15051e052a3406516bc0e24/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [creativetab](https://github.com/Minecolonies/minecolonies/blob/b5d461e3fce3021af15051e052a3406516bc0e24/src/main/java/com/minecolonies/coremod/creativetab): Add a 'package-info.java' file to document the 'creativetab' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [entity](https://github.com/Minecolonies/minecolonies/blob/b5d461e3fce3021af15051e052a3406516bc0e24/src/main/java/com/minecolonies/coremod/entity): Add a 'package-info.java' file to document the 'entity' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [basic](https://github.com/Minecolonies/minecolonies/blob/b5d461e3fce3021af15051e052a3406516bc0e24/src/main/java/com/minecolonies/coremod/entity/ai/basic): Add a 'package-info.java' file to document the 'basic' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [baker](https://github.com/Minecolonies/minecolonies/blob/b5d461e3fce3021af15051e052a3406516bc0e24/src/main/java/com/minecolonies/coremod/entity/ai/citizen/baker): Add a 'package-info.java' file to document the 'baker' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-19 02:42 UTC, Asherslab commented on src/main/resources/assets/minecolonies/book/minecolonies.xml
> +<book title="Minecolonies Resurrection" cover="gbook:covers/default" fontSize="0.6">
BTW this was NOT done by me, i just updated the version we use so that it actually loads

2017-06-19 07:49 UTC, xavierh reviewed
Does it mean you need to have the guidebook installed?

Asher: Apparently i can't comment on this:
You don't Have to have the guidebook mod installed, but if you do it'll have the Guide Book for minecolonies

2017-06-20 13:17 UTC, Raycoms commented
@Asherslab 
Two things: Are you able to do this for 1.10 as well?
And can you code that the player receives the book in the supplychest?

2017-06-20 13:21 UTC, MinecoloniesSonar commented
SonarQube analysis reported 26 issues
* ![MINOR][MINOR] 26 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/6489d25298fba547e231ed36a0a8ff371ddae14f/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/6489d25298fba547e231ed36a0a8ff371ddae14f/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/6489d25298fba547e231ed36a0a8ff371ddae14f/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/6489d25298fba547e231ed36a0a8ff371ddae14f/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/6489d25298fba547e231ed36a0a8ff371ddae14f/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/6489d25298fba547e231ed36a0a8ff371ddae14f/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [creativetab](https://github.com/Minecolonies/minecolonies/blob/6489d25298fba547e231ed36a0a8ff371ddae14f/src/main/java/com/minecolonies/coremod/creativetab): Add a 'package-info.java' file to document the 'creativetab' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [entity](https://github.com/Minecolonies/minecolonies/blob/6489d25298fba547e231ed36a0a8ff371ddae14f/src/main/java/com/minecolonies/coremod/entity): Add a 'package-info.java' file to document the 'entity' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [basic](https://github.com/Minecolonies/minecolonies/blob/6489d25298fba547e231ed36a0a8ff371ddae14f/src/main/java/com/minecolonies/coremod/entity/ai/basic): Add a 'package-info.java' file to document the 'basic' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [baker](https://github.com/Minecolonies/minecolonies/blob/6489d25298fba547e231ed36a0a8ff371ddae14f/src/main/java/com/minecolonies/coremod/entity/ai/citizen/baker): Add a 'package-info.java' file to document the 'baker' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-06-21 15:35 UTC, marchermans requested changes

2017-06-21 15:35 UTC, OrionDevelopment commented on build.gradle
> +    deobfCompile "gigaherz.guidebook:Guidebook-1.11.0:1.7.0"
use a constant like the other dependencies.

2017-07-01 00:18 UTC, closed without merging