Fix/barbarian despawn + colonists not spawning
ldtteam/minecolonies pull request #1486
Opened 2017-09-28 16:33 UTC by Raycoms

Bugfixes:

# Changes proposed in this pull request:
- Fixes a problem with colonists not spawning if daylight cycles are turned off.
- Fixes the problem with barbarians not spawning.
- Only executes barbarians checks once every random ticks.

Review please

2017-09-28 16:43 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/colony/Colony.java
>                  int respawnInterval = Configurations.gameplay.citizenRespawnInterval * 20;
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Assign this magic number 20 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

2017-09-28 16:43 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/colony/Colony.java
>                  respawnInterval -= (60 * townHall.getBuildingLevel());
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Assign this magic number 60 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

2017-09-28 16:43 UTC, MinecoloniesSonar commented
SonarQube analysis reported 60 issues
* ![MAJOR][MAJOR] 17 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/8daef2640f1b48a996dfdf179195020486981ba7/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.343 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L55](https://github.com/Minecolonies/minecolonies/blob/8daef2640f1b48a996dfdf179195020486981ba7/src/main/java/com/minecolonies/coremod/colony/Colony.java#L55): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 49 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L55](https://github.com/Minecolonies/minecolonies/blob/8daef2640f1b48a996dfdf179195020486981ba7/src/main/java/com/minecolonies/coremod/colony/Colony.java#L55): class "Colony" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L230](https://github.com/Minecolonies/minecolonies/blob/8daef2640f1b48a996dfdf179195020486981ba7/src/main/java/com/minecolonies/coremod/colony/Colony.java#L230): Assign this magic number 5 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L355](https://github.com/Minecolonies/minecolonies/blob/8daef2640f1b48a996dfdf179195020486981ba7/src/main/java/com/minecolonies/coremod/colony/Colony.java#L355): Remove this useless assignment to local variable "achievementKey". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Colony.java#L514](https://github.com/Minecolonies/minecolonies/blob/8daef2640f1b48a996dfdf179195020486981ba7/src/main/java/com/minecolonies/coremod/colony/Colony.java#L514): Remove this useless assignment to local variable "achievementCompound". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Colony.java#L635](https://github.com/Minecolonies/minecolonies/blob/8daef2640f1b48a996dfdf179195020486981ba7/src/main/java/com/minecolonies/coremod/colony/Colony.java#L635): Reduce the number of returns of this method 11, down to the maximum allowed 6. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1084](https://github.com/Minecolonies/minecolonies/blob/8daef2640f1b48a996dfdf179195020486981ba7/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1084): The Cyclomatic Complexity of this method "onWorldTick" is 17 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [Colony.java#L1250](https://github.com/Minecolonies/minecolonies/blob/8daef2640f1b48a996dfdf179195020486981ba7/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1250): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1252](https://github.com/Minecolonies/minecolonies/blob/8daef2640f1b48a996dfdf179195020486981ba7/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1252): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-09-28 16:58 UTC, cltnschlosser commented on src/main/java/com/minecolonies/coremod/colony/Colony.java
> +            if ((event.world.getTotalWorldTime() % CITIZEN_CLEANUP_TICK_INCREMENT) == 0 && areAllColonyChunksLoaded(event) && townHall != null)
We could improve server performance quite a bit by making a method that gives us total world time with a random offset unique to each colony (colonyID perhaps). That way this stuff wont all get called the same tick for every colony.

2017-09-28 17:00 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/colony/Colony.java
> +            if ((event.world.getTotalWorldTime() % CITIZEN_CLEANUP_TICK_INCREMENT) == 0 && areAllColonyChunksLoaded(event) && townHall != null)
I think I'll make that in a moment

2017-09-28 19:09 UTC, cltnschlosser commented on src/main/java/com/minecolonies/coremod/colony/Colony.java
>                  int respawnInterval = Configurations.gameplay.citizenRespawnInterval * 20;
Constants.TICKS_SECOND

2017-09-30 00:59 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/colony/Colony.java
>                  respawnInterval -= (60 * townHall.getBuildingLevel());
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Assign this magic number 60 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

2017-09-30 00:59 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/colony/Colony.java
>  public class Colony implements IColony
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 49 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') class "Colony" has 94 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)

2017-09-30 00:59 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/colony/Colony.java
> +import com.minecolonies.api.util.constant.Constants;
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Remove this unused import 'com.minecolonies.api.util.constant.Constants'. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

2017-09-30 00:59 UTC, MinecoloniesSonar commented
SonarQube analysis reported 60 issues
* ![MAJOR][MAJOR] 16 major
* ![MINOR][MINOR] 41 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/d9014c7db23e94508a8f6e932120894b21a05401/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.360 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L231](https://github.com/Minecolonies/minecolonies/blob/d9014c7db23e94508a8f6e932120894b21a05401/src/main/java/com/minecolonies/coremod/colony/Colony.java#L231): Assign this magic number 5 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L356](https://github.com/Minecolonies/minecolonies/blob/d9014c7db23e94508a8f6e932120894b21a05401/src/main/java/com/minecolonies/coremod/colony/Colony.java#L356): Remove this useless assignment to local variable "achievementKey". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Colony.java#L515](https://github.com/Minecolonies/minecolonies/blob/d9014c7db23e94508a8f6e932120894b21a05401/src/main/java/com/minecolonies/coremod/colony/Colony.java#L515): Remove this useless assignment to local variable "achievementCompound". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Colony.java#L636](https://github.com/Minecolonies/minecolonies/blob/d9014c7db23e94508a8f6e932120894b21a05401/src/main/java/com/minecolonies/coremod/colony/Colony.java#L636): Reduce the number of returns of this method 11, down to the maximum allowed 6. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1085](https://github.com/Minecolonies/minecolonies/blob/d9014c7db23e94508a8f6e932120894b21a05401/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1085): The Cyclomatic Complexity of this method "onWorldTick" is 18 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [Colony.java#L1274](https://github.com/Minecolonies/minecolonies/blob/d9014c7db23e94508a8f6e932120894b21a05401/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1274): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1276](https://github.com/Minecolonies/minecolonies/blob/d9014c7db23e94508a8f6e932120894b21a05401/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1276): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1278](https://github.com/Minecolonies/minecolonies/blob/d9014c7db23e94508a8f6e932120894b21a05401/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1278): Assign this magic number 128 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1471](https://github.com/Minecolonies/minecolonies/blob/d9014c7db23e94508a8f6e932120894b21a05401/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1471): Assign this magic number 0.5D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-09-30 01:17 UTC, MinecoloniesSonar commented
SonarQube analysis reported 58 issues
* ![MAJOR][MAJOR] 15 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/7a3ac87589c443f4c90597e126606a66d62af2ab/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.359 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L230](https://github.com/Minecolonies/minecolonies/blob/7a3ac87589c443f4c90597e126606a66d62af2ab/src/main/java/com/minecolonies/coremod/colony/Colony.java#L230): Assign this magic number 5 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L355](https://github.com/Minecolonies/minecolonies/blob/7a3ac87589c443f4c90597e126606a66d62af2ab/src/main/java/com/minecolonies/coremod/colony/Colony.java#L355): Remove this useless assignment to local variable "achievementKey". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Colony.java#L514](https://github.com/Minecolonies/minecolonies/blob/7a3ac87589c443f4c90597e126606a66d62af2ab/src/main/java/com/minecolonies/coremod/colony/Colony.java#L514): Remove this useless assignment to local variable "achievementCompound". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Colony.java#L635](https://github.com/Minecolonies/minecolonies/blob/7a3ac87589c443f4c90597e126606a66d62af2ab/src/main/java/com/minecolonies/coremod/colony/Colony.java#L635): Reduce the number of returns of this method 11, down to the maximum allowed 6. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1084](https://github.com/Minecolonies/minecolonies/blob/7a3ac87589c443f4c90597e126606a66d62af2ab/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1084): The Cyclomatic Complexity of this method "onWorldTick" is 18 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [Colony.java#L1273](https://github.com/Minecolonies/minecolonies/blob/7a3ac87589c443f4c90597e126606a66d62af2ab/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1273): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1275](https://github.com/Minecolonies/minecolonies/blob/7a3ac87589c443f4c90597e126606a66d62af2ab/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1275): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1277](https://github.com/Minecolonies/minecolonies/blob/7a3ac87589c443f4c90597e126606a66d62af2ab/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1277): Assign this magic number 128 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1470](https://github.com/Minecolonies/minecolonies/blob/7a3ac87589c443f4c90597e126606a66d62af2ab/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1470): Assign this magic number 0.5D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-10-01 02:03 UTC, MinecoloniesSonar commented
SonarQube analysis reported 58 issues
* ![MAJOR][MAJOR] 15 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/aa09c6cf1d066ee1873f10e8446c11b8e80c1336/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.359 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L230](https://github.com/Minecolonies/minecolonies/blob/aa09c6cf1d066ee1873f10e8446c11b8e80c1336/src/main/java/com/minecolonies/coremod/colony/Colony.java#L230): Assign this magic number 5 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L355](https://github.com/Minecolonies/minecolonies/blob/aa09c6cf1d066ee1873f10e8446c11b8e80c1336/src/main/java/com/minecolonies/coremod/colony/Colony.java#L355): Remove this useless assignment to local variable "achievementKey". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Colony.java#L514](https://github.com/Minecolonies/minecolonies/blob/aa09c6cf1d066ee1873f10e8446c11b8e80c1336/src/main/java/com/minecolonies/coremod/colony/Colony.java#L514): Remove this useless assignment to local variable "achievementCompound". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Colony.java#L635](https://github.com/Minecolonies/minecolonies/blob/aa09c6cf1d066ee1873f10e8446c11b8e80c1336/src/main/java/com/minecolonies/coremod/colony/Colony.java#L635): Reduce the number of returns of this method 11, down to the maximum allowed 6. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1084](https://github.com/Minecolonies/minecolonies/blob/aa09c6cf1d066ee1873f10e8446c11b8e80c1336/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1084): The Cyclomatic Complexity of this method "onWorldTick" is 18 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [Colony.java#L1273](https://github.com/Minecolonies/minecolonies/blob/aa09c6cf1d066ee1873f10e8446c11b8e80c1336/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1273): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1275](https://github.com/Minecolonies/minecolonies/blob/aa09c6cf1d066ee1873f10e8446c11b8e80c1336/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1275): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1277](https://github.com/Minecolonies/minecolonies/blob/aa09c6cf1d066ee1873f10e8446c11b8e80c1336/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1277): Assign this magic number 128 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1470](https://github.com/Minecolonies/minecolonies/blob/aa09c6cf1d066ee1873f10e8446c11b8e80c1336/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1470): Assign this magic number 0.5D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-10-01 12:14 UTC, marchermans requested changes

2017-10-01 12:14 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/colony/Colony.java
> +                    .forEachOrdered(subscribers::add);
Use a simple forEach instead of a Ordered.

2017-10-01 12:14 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/colony/Colony.java
> +        return world.getWorldTime() % (new Random().nextInt(CITIZEN_CLEANUP_TICK_INCREMENT*2) + 1) == 0;
Use a static Random some where. Or the worlds seed Random. Creating a new Random every tick is a big performance hit as it has to be seeded everytime.

2017-10-01 20:11 UTC, marchermans approved these changes

2017-10-01 20:12 UTC, merged

2017-10-01 20:24 UTC, MinecoloniesSonar commented
SonarQube analysis reported 58 issues
* ![MAJOR][MAJOR] 15 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/562eacc1fc20110ea6dc52029431492f972a135c/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.359 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L230](https://github.com/Minecolonies/minecolonies/blob/562eacc1fc20110ea6dc52029431492f972a135c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L230): Assign this magic number 5 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L355](https://github.com/Minecolonies/minecolonies/blob/562eacc1fc20110ea6dc52029431492f972a135c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L355): Remove this useless assignment to local variable "achievementKey". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Colony.java#L514](https://github.com/Minecolonies/minecolonies/blob/562eacc1fc20110ea6dc52029431492f972a135c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L514): Remove this useless assignment to local variable "achievementCompound". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [Colony.java#L635](https://github.com/Minecolonies/minecolonies/blob/562eacc1fc20110ea6dc52029431492f972a135c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L635): Reduce the number of returns of this method 11, down to the maximum allowed 6. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1084](https://github.com/Minecolonies/minecolonies/blob/562eacc1fc20110ea6dc52029431492f972a135c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1084): The Cyclomatic Complexity of this method "onWorldTick" is 18 which is greater than 15 authorized. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [Colony.java#L1273](https://github.com/Minecolonies/minecolonies/blob/562eacc1fc20110ea6dc52029431492f972a135c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1273): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1275](https://github.com/Minecolonies/minecolonies/blob/562eacc1fc20110ea6dc52029431492f972a135c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1275): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1277](https://github.com/Minecolonies/minecolonies/blob/562eacc1fc20110ea6dc52029431492f972a135c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1277): Assign this magic number 128 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1470](https://github.com/Minecolonies/minecolonies/blob/562eacc1fc20110ea6dc52029431492f972a135c/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1470): Assign this magic number 0.5D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'