Fix deliveryman
ldtteam/minecolonies pull request #2112
Opened 2018-01-30 12:56 UTC by Raycoms

# Changes proposed in this pull request:
 Improves the dman:
- Don't gather after deliver
- Don't deliver the same directly
- Don't gather requested items.

Review please

2018-01-30 13:03 UTC, BuildTeamLinter commented
SonarQube analysis reported 63 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 56 major
* ![MINOR][MINOR] 1 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L230](https://github.com/Minecolonies/minecolonies/blob/1b6afaecd317cc0ea5061abd3f59473851d157e2/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L230): Remove this call from a constructor to the overridable "setupRsDataStore" method. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1699)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1355](https://github.com/Minecolonies/minecolonies/blob/1b6afaecd317cc0ea5061abd3f59473851d157e2/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1355): Remove usage of generic wildcard type. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1425](https://github.com/Minecolonies/minecolonies/blob/1b6afaecd317cc0ea5061abd3f59473851d157e2/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1425): Remove usage of generic wildcard type. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1456](https://github.com/Minecolonies/minecolonies/blob/1b6afaecd317cc0ea5061abd3f59473851d157e2/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1456): Remove usage of generic wildcard type. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1468](https://github.com/Minecolonies/minecolonies/blob/1b6afaecd317cc0ea5061abd3f59473851d157e2/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1468): Remove usage of generic wildcard type. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1571](https://github.com/Minecolonies/minecolonies/blob/1b6afaecd317cc0ea5061abd3f59473851d157e2/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1571): Remove usage of generic wildcard type. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/1b6afaecd317cc0ea5061abd3f59473851d157e2/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/1b6afaecd317cc0ea5061abd3f59473851d157e2/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/1b6afaecd317cc0ea5061abd3f59473851d157e2/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/1b6afaecd317cc0ea5061abd3f59473851d157e2/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-01-30 13:11 UTC, marchermans requested changes

2018-01-30 13:11 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java
> +                        .anyMatch(token -> manager.getRequestForToken(token) instanceof IDeliverable
You are missing it here. You need the request.

2018-01-30 13:13 UTC, marchermans approved these changes

2018-01-30 13:20 UTC, BuildTeamLinter commented
SonarQube analysis reported 63 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 56 major
* ![MINOR][MINOR] 1 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L230](https://github.com/Minecolonies/minecolonies/blob/606c7a3eecb5df5bdc22e43cbb6d68274ac48405/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L230): Remove this call from a constructor to the overridable "setupRsDataStore" method. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1699)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1355](https://github.com/Minecolonies/minecolonies/blob/606c7a3eecb5df5bdc22e43cbb6d68274ac48405/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1355): Remove usage of generic wildcard type. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1425](https://github.com/Minecolonies/minecolonies/blob/606c7a3eecb5df5bdc22e43cbb6d68274ac48405/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1425): Remove usage of generic wildcard type. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1456](https://github.com/Minecolonies/minecolonies/blob/606c7a3eecb5df5bdc22e43cbb6d68274ac48405/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1456): Remove usage of generic wildcard type. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1468](https://github.com/Minecolonies/minecolonies/blob/606c7a3eecb5df5bdc22e43cbb6d68274ac48405/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1468): Remove usage of generic wildcard type. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [AbstractBuilding.java#L1571](https://github.com/Minecolonies/minecolonies/blob/606c7a3eecb5df5bdc22e43cbb6d68274ac48405/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L1571): Remove usage of generic wildcard type. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/606c7a3eecb5df5bdc22e43cbb6d68274ac48405/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/606c7a3eecb5df5bdc22e43cbb6d68274ac48405/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/606c7a3eecb5df5bdc22e43cbb6d68274ac48405/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/606c7a3eecb5df5bdc22e43cbb6d68274ac48405/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-01-30 13:23 UTC, merged

2018-02-25 17:06 UTC, lunadragnstar commented
It would also be nice if the deliveryman didn't drop items in chests instead of warehouse. (I found the lumberjack chest full of eggs from the chickenherder. They should be dropping that off at the warehouse.