Feature/bigger schems
ldtteam/minecolonies pull request #2287
Opened 2018-03-05 02:26 UTC by Raycoms

# Changes proposed in this pull request:
- Allows to scan bigger schematics
- Limits build tool rendering to 100k blocks.
- Allows to send bigger schematics over to the server and cache them there.

Review please

2018-03-05 02:32 UTC, BuildTeamLinter commented on src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java
> +                    //todo!!!!
![INFO](https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO') Complete the task associated to this TODO comment. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1135)

2018-03-05 02:32 UTC, BuildTeamLinter commented on src/main/java/com/minecolonies/coremod/colony/Structures.java
> +    public static boolean handleSaveSchematicMessage(final byte[] bytes, final UUID id, final int pieces, final int piece)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Reduce the number of returns of this method 7, down to the maximum allowed 6. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Refactor this method to reduce its Cognitive Complexity from 28 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

2018-03-05 02:32 UTC, BuildTeamLinter commented on src/main/java/com/minecolonies/coremod/colony/Structures.java
>              Log.getLogger().warn("Structure " + structureName + " is " + compressed.length + " bytes when compress, maximum allowed is " + maxSize + " bytes.");
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') A "NullPointerException" could be thrown; "compressed" is nullable here. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2259)

2018-03-05 02:32 UTC, BuildTeamLinter commented on src/main/java/com/minecolonies/coremod/colony/Structures.java
> +                if(MathUtils.nanoSecondsToSeconds(System.nanoTime() - schemTuple.getFirst()) > 60)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Assign this magic number 60 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

2018-03-05 02:32 UTC, BuildTeamLinter commented on src/main/java/com/minecolonies/coremod/network/messages/SchematicRequestMessage.java
> +import com.minecolonies.coremod.util.StructureWrapper;
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Remove this unused import 'com.minecolonies.coremod.util.StructureWrapper'. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

2018-03-05 02:32 UTC, BuildTeamLinter commented on src/main/java/com/minecolonies/structures/helpers/Structure.java
>  public class Structure
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 36 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)

2018-03-05 02:32 UTC, BuildTeamLinter commented on src/main/java/com/minecolonies/structures/helpers/Structure.java
>              for (final Template.BlockInfo aBlockList : blockList)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Reduce the total number of break and continue statements in this loop to use at most one. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Combine this loop with the one that starts on line 563. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3047)

2018-03-05 02:32 UTC, BuildTeamLinter commented on src/main/java/com/minecolonies/coremod/network/messages/SaveScanMessage.java
>  import net.minecraftforge.fml.common.network.ByteBufUtils;
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Remove this unused import 'net.minecraftforge.fml.common.network.ByteBufUtils'. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

2018-03-05 02:32 UTC, BuildTeamLinter commented
SonarQube analysis reported 68 issues
* ![MAJOR][MAJOR] 61 major
* ![MINOR][MINOR] 4 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/ab78b26d8c40ec02a8f713dddd1dced452b75d26/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/ab78b26d8c40ec02a8f713dddd1dced452b75d26/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L46](https://github.com/Minecolonies/minecolonies/blob/ab78b26d8c40ec02a8f713dddd1dced452b75d26/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L46): class "WindowBuildTool" has 41 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L811](https://github.com/Minecolonies/minecolonies/blob/ab78b26d8c40ec02a8f713dddd1dced452b75d26/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L811): Refactor this method to reduce its Cognitive Complexity from 23 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L922](https://github.com/Minecolonies/minecolonies/blob/ab78b26d8c40ec02a8f713dddd1dced452b75d26/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L922): Refactor this method to reduce its Cognitive Complexity from 24 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/ab78b26d8c40ec02a8f713dddd1dced452b75d26/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/ab78b26d8c40ec02a8f713dddd1dced452b75d26/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [Structures.java#L174](https://github.com/Minecolonies/minecolonies/blob/ab78b26d8c40ec02a8f713dddd1dced452b75d26/src/main/java/com/minecolonies/coremod/colony/Structures.java#L174): Either log or rethrow this exception. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/ab78b26d8c40ec02a8f713dddd1dced452b75d26/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/ab78b26d8c40ec02a8f713dddd1dced452b75d26/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-03-05 12:55 UTC, BuildTeamLinter commented on src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java
> +                            if (i == pieces)
![CRITICAL](https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL') Refactor this code to not nest more than 5 if/for/while/switch/try statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS134)

2018-03-05 12:55 UTC, BuildTeamLinter commented
SonarQube analysis reported 67 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 61 major
* ![MINOR][MINOR] 4 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/ce77d85e3534084ba9d642c1d2dd236952ec187d/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/ce77d85e3534084ba9d642c1d2dd236952ec187d/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L46](https://github.com/Minecolonies/minecolonies/blob/ce77d85e3534084ba9d642c1d2dd236952ec187d/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L46): class "WindowBuildTool" has 41 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L811](https://github.com/Minecolonies/minecolonies/blob/ce77d85e3534084ba9d642c1d2dd236952ec187d/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L811): Refactor this method to reduce its Cognitive Complexity from 30 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L930](https://github.com/Minecolonies/minecolonies/blob/ce77d85e3534084ba9d642c1d2dd236952ec187d/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L930): Refactor this method to reduce its Cognitive Complexity from 24 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/ce77d85e3534084ba9d642c1d2dd236952ec187d/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/ce77d85e3534084ba9d642c1d2dd236952ec187d/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [Structures.java#L174](https://github.com/Minecolonies/minecolonies/blob/ce77d85e3534084ba9d642c1d2dd236952ec187d/src/main/java/com/minecolonies/coremod/colony/Structures.java#L174): Either log or rethrow this exception. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/ce77d85e3534084ba9d642c1d2dd236952ec187d/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/ce77d85e3534084ba9d642c1d2dd236952ec187d/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-03-05 18:43 UTC, BuildTeamLinter commented
SonarQube analysis reported 65 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 60 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/99725b304466d82cafcf1450d561267363741466/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/99725b304466d82cafcf1450d561267363741466/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L46](https://github.com/Minecolonies/minecolonies/blob/99725b304466d82cafcf1450d561267363741466/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L46): class "WindowBuildTool" has 41 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L811](https://github.com/Minecolonies/minecolonies/blob/99725b304466d82cafcf1450d561267363741466/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L811): Refactor this method to reduce its Cognitive Complexity from 30 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L930](https://github.com/Minecolonies/minecolonies/blob/99725b304466d82cafcf1450d561267363741466/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L930): Refactor this method to reduce its Cognitive Complexity from 24 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/99725b304466d82cafcf1450d561267363741466/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/99725b304466d82cafcf1450d561267363741466/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [Structures.java#L174](https://github.com/Minecolonies/minecolonies/blob/99725b304466d82cafcf1450d561267363741466/src/main/java/com/minecolonies/coremod/colony/Structures.java#L174): Either log or rethrow this exception. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [Structures.java#L286](https://github.com/Minecolonies/minecolonies/blob/99725b304466d82cafcf1450d561267363741466/src/main/java/com/minecolonies/coremod/colony/Structures.java#L286): Remove this useless assignment to local variable "maxSize". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/99725b304466d82cafcf1450d561267363741466/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-03-05 20:51 UTC, BuildTeamLinter commented
SonarQube analysis reported 70 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 62 major
* ![MINOR][MINOR] 6 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/398cea2778305f62194250d4c6f52508f18c48d6/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/398cea2778305f62194250d4c6f52508f18c48d6/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L46](https://github.com/Minecolonies/minecolonies/blob/398cea2778305f62194250d4c6f52508f18c48d6/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L46): class "WindowBuildTool" has 41 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L811](https://github.com/Minecolonies/minecolonies/blob/398cea2778305f62194250d4c6f52508f18c48d6/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L811): Refactor this method to reduce its Cognitive Complexity from 30 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L930](https://github.com/Minecolonies/minecolonies/blob/398cea2778305f62194250d4c6f52508f18c48d6/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L930): Refactor this method to reduce its Cognitive Complexity from 24 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/398cea2778305f62194250d4c6f52508f18c48d6/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/398cea2778305f62194250d4c6f52508f18c48d6/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [Structures.java#L174](https://github.com/Minecolonies/minecolonies/blob/398cea2778305f62194250d4c6f52508f18c48d6/src/main/java/com/minecolonies/coremod/colony/Structures.java#L174): Either log or rethrow this exception. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [Structures.java#L286](https://github.com/Minecolonies/minecolonies/blob/398cea2778305f62194250d4c6f52508f18c48d6/src/main/java/com/minecolonies/coremod/colony/Structures.java#L286): Remove this useless assignment to local variable "maxSize". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/398cea2778305f62194250d4c6f52508f18c48d6/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-03-06 11:58 UTC, marchermans requested changes

2018-03-06 11:58 UTC, OrionDevelopment commented on src/main/resources/assets/minecolonies/lang/en_us.lang
> +tile.minecolonies.blockshingleslab_sandstone.name=Sandstone Shingle Slab
I think that this does not belong here.

2018-03-06 12:49 UTC, BuildTeamLinter commented
SonarQube analysis reported 70 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 62 major
* ![MINOR][MINOR] 6 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/89865655daa9e6f70ef8c4eda921c3a278e5025b/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/89865655daa9e6f70ef8c4eda921c3a278e5025b/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L46](https://github.com/Minecolonies/minecolonies/blob/89865655daa9e6f70ef8c4eda921c3a278e5025b/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L46): class "WindowBuildTool" has 41 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L811](https://github.com/Minecolonies/minecolonies/blob/89865655daa9e6f70ef8c4eda921c3a278e5025b/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L811): Refactor this method to reduce its Cognitive Complexity from 30 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [WindowBuildTool.java#L930](https://github.com/Minecolonies/minecolonies/blob/89865655daa9e6f70ef8c4eda921c3a278e5025b/src/main/java/com/minecolonies/coremod/client/gui/WindowBuildTool.java#L930): Refactor this method to reduce its Cognitive Complexity from 24 to the 20 allowed. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/89865655daa9e6f70ef8c4eda921c3a278e5025b/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/89865655daa9e6f70ef8c4eda921c3a278e5025b/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [Structures.java#L174](https://github.com/Minecolonies/minecolonies/blob/89865655daa9e6f70ef8c4eda921c3a278e5025b/src/main/java/com/minecolonies/coremod/colony/Structures.java#L174): Either log or rethrow this exception. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [Structures.java#L286](https://github.com/Minecolonies/minecolonies/blob/89865655daa9e6f70ef8c4eda921c3a278e5025b/src/main/java/com/minecolonies/coremod/colony/Structures.java#L286): Remove this useless assignment to local variable "maxSize". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1854)
1. ![MAJOR][MAJOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/89865655daa9e6f70ef8c4eda921c3a278e5025b/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-03-06 13:13 UTC, merged