Lang fixes, monster eggs hopefully fixed, the list of workers is now scrollable
ldtteam/minecolonies pull request #2527
Opened 2018-06-11 16:17 UTC by Nightenom

Closes #2526

# Changes proposed in this pull request:
- Add missing strings for the guard update
- Replaced hopefully all monster eggs in medieval warehouses lvl 5
- The list of workers in the townhall is now scrollable

Review please

2018-06-11 16:56 UTC, marchermans requested changes
Build failure. Please fix the broken test.

2018-06-13 12:30 UTC, Nightenom commented on src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java
> +                if (index == 2)
It's commented above these conditions

2018-06-13 12:37 UTC, BuildTeamLinter commented
SonarQube analysis reported 50 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 49 major

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [WindowTownHall.java#L1048](https://github.com/ldtteam/minecolonies/blob/cc7ef1abba811fff8185434d0d359153d4f8f874/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L1048): Add a default case to this switch. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ASwitchLastCaseIsDefaultCheck)
1. ![MAJOR][MAJOR] [blocks#](https://github.com/ldtteam/minecolonies/blob/cc7ef1abba811fff8185434d0d359153d4f8f874/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/ldtteam/minecolonies/blob/cc7ef1abba811fff8185434d0d359153d4f8f874/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L47](https://github.com/ldtteam/minecolonies/blob/cc7ef1abba811fff8185434d0d359153d4f8f874/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L47): class "WindowTownHall" has 41 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L915](https://github.com/ldtteam/minecolonies/blob/cc7ef1abba811fff8185434d0d359153d4f8f874/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L915): Reduce this anonymous class number of lines from 41 to at most 40, or make it a named class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [render#](https://github.com/ldtteam/minecolonies/blob/cc7ef1abba811fff8185434d0d359153d4f8f874/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [permissions#](https://github.com/ldtteam/minecolonies/blob/cc7ef1abba811fff8185434d0d359153d4f8f874/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [requestable#](https://github.com/ldtteam/minecolonies/blob/cc7ef1abba811fff8185434d0d359153d4f8f874/src/main/java/com/minecolonies/coremod/colony/requestable#): Add a 'package-info.java' file to document the 'requestable' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [data#](https://github.com/ldtteam/minecolonies/blob/cc7ef1abba811fff8185434d0d359153d4f8f874/src/main/java/com/minecolonies/coremod/colony/requestsystem/data#): Add a 'package-info.java' file to document the 'data' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [init#](https://github.com/ldtteam/minecolonies/blob/cc7ef1abba811fff8185434d0d359153d4f8f874/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2018-06-13 13:59 UTC, Raycoms commented
:shipit:

2018-06-13 20:51 UTC, merged

2018-06-13 21:24 UTC, BuildTeamLinter commented
SonarQube analysis reported 50 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 49 major

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [WindowTownHall.java#L1048](https://github.com/ldtteam/minecolonies/blob/a4a66901d67123b1da0480f9867c77ad97d6fb39/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L1048): Add a default case to this switch. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ASwitchLastCaseIsDefaultCheck)
1. ![MAJOR][MAJOR] [blocks#](https://github.com/ldtteam/minecolonies/blob/a4a66901d67123b1da0480f9867c77ad97d6fb39/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/ldtteam/minecolonies/blob/a4a66901d67123b1da0480f9867c77ad97d6fb39/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L47](https://github.com/ldtteam/minecolonies/blob/a4a66901d67123b1da0480f9867c77ad97d6fb39/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L47): class "WindowTownHall" has 41 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L915](https://github.com/ldtteam/minecolonies/blob/a4a66901d67123b1da0480f9867c77ad97d6fb39/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L915): Reduce this anonymous class number of lines from 41 to at most 40, or make it a named class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [render#](https://github.com/ldtteam/minecolonies/blob/a4a66901d67123b1da0480f9867c77ad97d6fb39/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [permissions#](https://github.com/ldtteam/minecolonies/blob/a4a66901d67123b1da0480f9867c77ad97d6fb39/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [requestable#](https://github.com/ldtteam/minecolonies/blob/a4a66901d67123b1da0480f9867c77ad97d6fb39/src/main/java/com/minecolonies/coremod/colony/requestable#): Add a 'package-info.java' file to document the 'requestable' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [data#](https://github.com/ldtteam/minecolonies/blob/a4a66901d67123b1da0480f9867c77ad97d6fb39/src/main/java/com/minecolonies/coremod/colony/requestsystem/data#): Add a 'package-info.java' file to document the 'data' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [init#](https://github.com/ldtteam/minecolonies/blob/a4a66901d67123b1da0480f9867c77ad97d6fb39/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'