Fix/rs
ldtteam/minecolonies pull request #2630
Opened 2018-07-15 13:03 UTC by Raycoms

Fix request handling

# Changes proposed in this pull request:
- Fixes asynch requests
- Fixes retrying resolver

Review please

2018-07-15 13:30 UTC, LDTTeam-Buildsystem submitted a review, later dismissed
#### Analysis Complete
##### Statistics:
|        | Count | New  | Old  | Diff |
| ------ |:-----:|:----:|:----:|:----:|
| Total  | 34017 | 3655 | 2722 | +933 |
| Errors |  593  |  26  |  17  |  +9  |
##### More Information:
- [Analysis - Full](https://teamcity.minecolonies.com/viewLog.html?buildId=11896&tab=Inspection&buildTypeId=bt88)

2018-07-16 00:28 UTC, LDTTeam-Buildsystem submitted a review, later dismissed
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  | 34017 |  0  |  0  |  0   |
| Errors |  593  |  0  |  0  |  0   |
##### More Information:

2018-07-16 00:34 UTC, LDTTeam-Buildsystem submitted a review, later dismissed
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

2018-07-16 01:25 UTC, LDTTeam-Buildsystem approved these changes
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  | 34011 |  7  | 13  |  -6  |
| Errors |  593  |  0  |  0  |  0   |
##### More Information:
- [Analysis - Full](https://teamcity.minecolonies.com/viewLog.html?buildId=12116&tab=Inspection&buildTypeId=bt88)

2018-07-16 07:28 UTC, marchermans requested changes
One small Thing.

2018-07-16 07:28 UTC, marchermans commented on src/api/java/com/minecolonies/api/colony/requestsystem/requestable/Stack.java
> +            return OreDictionary.itemMatches(getStack(), stack, matchMeta);
Please revert this Change. This contraticts the other behaviour of Stack.

2018-07-16 13:31 UTC, merged