Fix/armor request
ldtteam/minecolonies pull request #2764
Opened 2018-08-09 11:41 UTC by Raycoms

Closes #2715 

# Changes proposed in this pull request:
- Style based rework of the Guard code (move specific code into specific classes)
- Rework the requesting code:
1) It makes sure they request things only when they need to
2) It makes sure they wear the best armor they can wear of what they have
3) It dumps armor they don't need in their chest
4) They don't take armor they don't need from the chest

Leather armor is level 0-20 (workerlevel) and building level 1-3
Gold is 0-20 as well and 1-4
Chain is 0-20 for 2-5
Iron is 5-30 for 3-5
Fiamond is 15-99 for 4-5

Review please

2018-08-09 11:52 UTC, marchermans requested changes

2018-08-09 11:52 UTC, OrionDevelopment commented on src/api/java/com/minecolonies/api/entity/ai/citizen/guards/GuardItems.java
> +public class GuardItems
You can make this extend Predicate<ItemStack> to easilly check if this is a Matching GuardItem

2018-08-09 11:52 UTC, OrionDevelopment commented on src/api/java/com/minecolonies/api/entity/ai/citizen/guards/GuardItems.java
> +public class GuardItems
Since this class has a lot of configurable options, consider creating a Builder class instead of using the constructor.

2018-08-09 11:52 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/blockout/controls/TextField.java
> -    public int getMaxTextLength()
I am guessing not in use?

2018-08-09 11:52 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> +        leatherLevelArmor.add(new GuardItems(ToolType.BOOTS, EntityEquipmentSlot.FEET,  ARMOR_LEVEL_LEATHER, 1, 0, 20, 1, 3));
Constants please, I have no idea what all these numbers do. Or use a Builder class for GuardItems with properly named setter methods.

2018-08-09 12:13 UTC, LDTTeam-Buildsystem submitted a review, later dismissed
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  | 39766 |  3  | 39  | -36  |
| Errors |  596  |  0  |  0  |  0   |
##### More Information:
- [Analysis - Full](https://teamcity.minecolonies.com/viewLog.html?buildId=15690&tab=Inspection&buildTypeId=bt88)

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
>  import net.minecraft.inventory.EntityEquipmentSlot;
### Errors:
- Unused import import net.minecraftforge.items.IItemHandler;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
>  import net.minecraft.item.ItemArmor;
### Errors:
- Unused import import net.minecraftforge.items.wrapper.InvWrapper;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
>  import com.minecolonies.api.colony.permissions.Action;
### Errors:
- Unused import import com.minecolonies.api.colony.permissions.Action;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> -import com.minecolonies.api.compatibility.tinkers.TinkersWeaponHelper;
### Errors:
- Unused import import com.minecolonies.api.entity.ai.citizen.guards.GuardItems;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> +    public final List<List<GuardItems>> itemsNeeded = new ArrayList<>();
### Errors:
- Can be package-private

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> -import com.minecolonies.api.configuration.Configurations;
### Errors:
- Unused import import com.minecolonies.api.entity.ai.citizen.guards.GuardTask;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> +import com.minecolonies.api.entity.ai.citizen.guards.GuardItems;
### Errors:
- Unused import import com.minecolonies.api.util.InventoryFunctions;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
>  import com.minecolonies.api.entity.ai.citizen.guards.GuardTask;
### Errors:
- Unused import import com.minecolonies.api.util.InventoryUtils;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
>  import net.minecraft.util.math.AxisAlignedBB;
### Errors:
- Unused import import static com.minecolonies.api.util.constant.ColonyConstants.TEAM_COLONY_NAME;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> -import com.minecolonies.api.util.BlockPosUtil;
### Errors:
- Unused import import com.minecolonies.api.util.ItemStackUtils;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
>  import net.minecraft.util.math.BlockPos;
### Errors:
- Unused import import static com.minecolonies.api.util.constant.ToolLevelConstants.*;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
>  import com.minecolonies.api.util.InventoryFunctions;
### Errors:
- Unused import import com.minecolonies.api.util.constant.Constants;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
>  import com.minecolonies.api.util.constant.TranslationConstants;
### Errors:
- Unused import import com.minecolonies.api.util.constant.TranslationConstants;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
>  import com.minecolonies.coremod.entity.ai.util.AITarget;
### Errors:
- Unused import import net.minecraft.entity.EntityLivingBase;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> -import com.minecolonies.coremod.tileentities.TileEntityColonyBuilding;
### Errors:
- Unused import import net.minecraft.entity.player.EntityPlayer;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> -import net.minecraft.enchantment.EnchantmentHelper;
### Errors:
- Unused import import net.minecraft.inventory.EntityEquipmentSlot;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
>  import net.minecraft.entity.EntityLivingBase;
### Errors:
- Unused import import net.minecraft.item.ItemArmor;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> -import net.minecraft.entity.MoverType;
### Errors:
- Unused import import net.minecraft.item.ItemStack;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
>  import net.minecraft.entity.player.EntityPlayer;
### Errors:
- Unused import import net.minecraft.potion.PotionEffect;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
>      public final List<ToolType>  toolsNeeded = new ArrayList<>();
### Errors:
- Can be package-private

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> -import net.minecraft.entity.projectile.EntityTippedArrow;
### Errors:
- Unused import import net.minecraft.util.math.AxisAlignedBB;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> -import net.minecraft.init.Items;
### Errors:
- Unused import import net.minecraft.util.math.BlockPos;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> -import net.minecraft.init.SoundEvents;
### Errors:
- Unused import import net.minecraft.util.text.TextComponentTranslation;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
> +import net.minecraft.util.math.MathHelper;
### Errors:
- Unused import import net.minecraft.util.math.MathHelper;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
> +import net.minecraftforge.items.wrapper.InvWrapper;
### Errors:
- Unused import import net.minecraftforge.items.wrapper.InvWrapper;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
> +import com.minecolonies.api.util.BlockPosUtil;
### Errors:
- Unused import import com.minecolonies.api.util.BlockPosUtil;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
> +import com.minecolonies.api.util.InventoryUtils;
### Errors:
- Unused import import com.minecolonies.api.util.InventoryUtils;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
>  import com.minecolonies.api.util.constant.ToolType;
### Errors:
- Unused import import com.minecolonies.api.util.constant.ToolType;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
> +import static com.minecolonies.coremod.entity.ai.citizen.guard.GuardConstants.BASIC_VOLUME;
### Errors:
- Unused import import static com.minecolonies.coremod.entity.ai.citizen.guard.GuardConstants.BASIC_VOLUME;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
> +import static com.minecolonies.coremod.entity.ai.citizen.guard.GuardConstants.MOVE_MINIMAL;
### Errors:
- Unused import import static com.minecolonies.coremod.entity.ai.citizen.guard.GuardConstants.MOVE_MINIMAL;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
> +import net.minecraft.entity.EntityLivingBase;
### Errors:
- Unused import import net.minecraft.entity.EntityLivingBase;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
> +import net.minecraft.entity.MoverType;
### Errors:
- Unused import import net.minecraft.entity.MoverType;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
> +import net.minecraft.entity.projectile.EntityTippedArrow;
### Errors:
- Unused import import net.minecraft.entity.projectile.EntityTippedArrow;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
> +import net.minecraft.init.SoundEvents;
### Errors:
- Unused import import net.minecraft.init.SoundEvents;

2018-08-09 12:13 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
> +import net.minecraft.util.EnumHand;
### Errors:
- Unused import import net.minecraft.util.EnumHand;

2018-08-09 14:18 UTC, Raycoms commented on src/main/java/com/minecolonies/blockout/controls/TextField.java
> -    public int getMaxTextLength()
Yeah, not in use

2018-08-09 14:41 UTC, LDTTeam-Buildsystem submitted a review, later dismissed
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

2018-08-09 17:55 UTC, marchermans submitted a review, later dismissed

2018-08-09 17:55 UTC, OrionDevelopment commented on src/api/java/com/minecolonies/api/entity/ai/citizen/guards/GuardGearBuilder.java
> +public class GuardGearBuilder
This is not what I mean with a builder class, but okey……………. Try have IntelliJ generate one for you.

2018-08-09 17:55 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> +        itemsNeeded.add(GuardGearBuilder.buildGearForLevel(ARMOR_LEVEL_LEATHER, LEATHER_LEVEL_RANGE, LEATHER_BUILDING_LEVEL_RANGE));
Even though it is not what I mean with a Builder class, this makes it way more readable too.

2018-08-09 18:58 UTC, LDTTeam-Buildsystem submitted a review, later dismissed
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  | 39787 |  0  |  3  |  -3  |
| Errors |  596  |  0  |  0  |  0   |
##### More Information:

2018-08-10 08:42 UTC, marchermans submitted a review, later dismissed

2018-08-10 21:06 UTC, LDTTeam-Buildsystem approved these changes
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  | 39793 | 13  |  7  |  +6  |
| Errors |  596  |  0  |  0  |  +0  |
##### More Information:
- [Analysis - Full](https://teamcity.minecolonies.com/viewLog.html?buildId=15776&tab=Inspection&buildTypeId=bt88)

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/colony/managers/BarbarianManager.java
>  import static com.minecolonies.api.util.constant.ColonyConstants.*;
### Errors:
- Unused import import static com.minecolonies.api.util.constant.ColonyConstants.*;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/colony/managers/BarbarianManager.java
> @@ -50,7 +53,7 @@
### Errors:
- Unused import import static com.minecolonies.api.util.constant.Constants.HALF_A_CIRCLE;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/colony/managers/BarbarianManager.java
> +import net.minecraft.entity.Entity;
### Errors:
- Unused import import net.minecraft.entity.Entity;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/colony/managers/BarbarianManager.java
>  import net.minecraft.util.EnumFacing;
### Errors:
- Unused import import net.minecraft.util.EnumFacing;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/colony/managers/BarbarianManager.java
>  import net.minecraft.util.Tuple;
### Errors:
- Unused import import net.minecraft.util.Tuple;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/colony/managers/BarbarianManager.java
>  import net.minecraft.util.math.BlockPos;
### Errors:
- Unused import import net.minecraft.util.math.BlockPos;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/colony/managers/BarbarianManager.java
>  import net.minecraft.world.World;
### Errors:
- Unused import import net.minecraft.world.World;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/colony/managers/BarbarianManager.java
> +import net.minecraft.world.WorldServer;
### Errors:
- Unused import import net.minecraft.world.WorldServer;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/colony/managers/IBarbarianManager.java
>  import net.minecraft.util.EnumFacing;
### Errors:
- Unused import import net.minecraft.util.EnumFacing;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/colony/managers/IBarbarianManager.java
>  import net.minecraft.util.math.BlockPos;
### Errors:
- Unused import import net.minecraft.util.math.BlockPos;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/colony/managers/IBarbarianManager.java
> +import net.minecraft.world.WorldServer;
### Errors:
- Unused import import net.minecraft.world.WorldServer;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java
>  import net.minecraft.util.text.TextComponentTranslation;
### Errors:
- Unused import import net.minecraft.util.text.TextComponentTranslation;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java
> +import net.minecraft.world.WorldServer;
### Errors:
- Unused import import net.minecraft.world.WorldServer; 
- Unused import import static com.minecolonies.api.util.constant.NbtTagConstants.*;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java
>  import net.minecraftforge.common.capabilities.Capability;
### Errors:
- Unused import import net.minecraftforge.common.capabilities.Capability;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java
>  import net.minecraftforge.items.CapabilityItemHandler;
### Errors:
- Unused import import net.minecraftforge.items.CapabilityItemHandler;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java
>  import net.minecraftforge.items.wrapper.InvWrapper;
### Errors:
- Unused import import net.minecraftforge.items.wrapper.InvWrapper;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/mobs/barbarians/AbstractEntityBarbarian.java
>  import net.minecraft.util.SoundEvent;
### Errors:
- Unused import import net.minecraft.util.SoundEvent;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/mobs/barbarians/AbstractEntityBarbarian.java
>  import net.minecraft.world.DifficultyInstance;
### Errors:
- Unused import import net.minecraft.world.DifficultyInstance;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/mobs/barbarians/AbstractEntityBarbarian.java
>  import net.minecraft.world.World;
### Errors:
- Unused import import net.minecraft.world.World;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/mobs/barbarians/AbstractEntityBarbarian.java
> +import net.minecraft.world.WorldServer;
### Errors:
- Unused import import net.minecraft.world.WorldServer;

2018-08-10 21:06 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/mobs/barbarians/AbstractEntityBarbarian.java
>  import javax.annotation.Nullable;
### Errors:
- Unused import import javax.annotation.Nullable;

2018-08-10 21:12 UTC, LDTTeam-Buildsystem approved these changes
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  | 39789 |  3  |  7  |  -4  |
| Errors |  596  |  0  |  0  |  0   |
##### More Information:
- [Analysis - Full](https://teamcity.minecolonies.com/viewLog.html?buildId=15788&tab=Inspection&buildTypeId=bt88)

2018-08-10 21:22 UTC, LDTTeam-Buildsystem approved these changes
#### Analysis Complete
##### Statistics:
|        | Count | New  | Old  | Diff  |
| ------ |:-----:|:----:|:----:|:-----:|
| Total  | 34779 | 3019 | 8029 | -5010 |
| Errors |  247  |  3   | 352  | -349  |
##### More Information:
- [Analysis - Full](https://teamcity.minecolonies.com/viewLog.html?buildId=15800&tab=Inspection&buildTypeId=bt88)

2018-08-10 21:22 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIKnight.java
>      public EntityAIKnight(@NotNull final JobKnight job)
### Errors:
- Parameter 'job' of concrete class JobKnight

2018-08-10 21:22 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIKnight.java
> @@ -34,15 +49,16 @@
### Errors:
- EntityAIKnight is too deep in inheritance tree (inheritance depth = 7) 
- Class 'EntityAIKnight' has too many dependencies (14 > 10)
- Class 'EntityAIKnight' has too many transitive dependencies (509 > 35)
- Class 'EntityAIKnight' has too many transitive dependencies (696 > 35)

2018-08-10 21:22 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
>      public EntityAIRanger(@NotNull final JobRanger job)
### Errors:
- Parameter 'job' of concrete class JobRanger

2018-08-10 21:22 UTC, LDTTeam-Buildsystem commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/EntityAIRanger.java
>  public class EntityAIRanger extends AbstractEntityAIGuard<JobRanger>
### Errors:
- EntityAIRanger is too deep in inheritance tree (inheritance depth = 7) 
- Class 'EntityAIRanger' has too many dependencies (18 > 10)
- Class 'EntityAIRanger' has too many transitive dependencies (509 > 35)
- Class 'EntityAIRanger' has too many transitive dependencies (696 > 35)

2018-08-11 19:07 UTC, merged