Dynamic tree compat
ldtteam/minecolonies pull request #2942
Opened 2018-10-07 16:57 UTC by someaddons

Closes https://github.com/ldtteam/minecolonies/issues/2316

# Changes proposed in this pull request:
Adding compability for Dynamic Trees

Review please

2018-10-07 17:11 UTC, LDTTeam-Buildsystem submitted a review, later dismissed
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

2018-10-07 17:31 UTC, Nightenom requested changes
Good job except formatting and scoping 
In general, follow codacy comments

2018-10-07 17:31 UTC, Nightenom commented on src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
>      public ItemStack getSaplingForLeave(final IBlockState block)
Can you also rename all methods with leave -> leaf problem?

2018-10-07 17:31 UTC, Nightenom commented on src/api/java/com/minecolonies/api/compatibility/Compatibility.java
> +    public static boolean plantDynamicSapling(World world, BlockPos location, ItemStack sapling)
We make all method parameters `final`

2018-10-07 17:31 UTC, Nightenom commented on src/api/java/com/minecolonies/api/compatibility/Compatibility.java
> +        return DynamicTreeCompat.plantDynamicSapling(world,location,sapling);
spaces after `,`

> Raycoms (copied):
> Can you please update the formatting to fit the general style?
> Especially the bracket style, there is a formatter xml file in the repo you can download and import with intellij

2018-10-07 17:31 UTC, Nightenom commented on src/api/java/com/minecolonies/api/compatibility/dynamicTrees/DynamicTreeCompat.java
> +    {}
extend with new line, find somewhere (e.g. all constants in utils) how we write private constructors

2018-10-07 17:31 UTC, Nightenom commented on src/api/java/com/minecolonies/api/compatibility/dynamicTrees/DynamicTreeCompat.java
> +    private final String DynModId = "dynamictrees";
if it's a constant try to use uppercase and underscore

2018-10-07 17:31 UTC, Nightenom commented on src/api/java/com/minecolonies/api/compatibility/dynamicTrees/DynamicTreeCompat.java
> +            if(toolToUse != null)
this, plus a space between if ->
```
if ()
{
  ...
}
```

2018-10-07 17:31 UTC, Nightenom commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java
> +                if (!mineBlock(log, workFrom,false,false,Compatibility.getDynamicTreeBreakAction(world,log,worker.getHeldItem(EnumHand.MAIN_HAND),worker.getPosition())))
If line is long you can try splitting it into more lines (not necessary)

2018-10-07 17:31 UTC, Nightenom commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java
> +                this.getOwnBuilding().getColony().getStatsManager().incrementStatistic("saplings");
no need to use statsmanager or achievements, at least I deleted it in upcoming advancements PR

2018-10-07 17:31 UTC, Nightenom commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/EntityAIWorkLumberjack.java
> +        return !ItemStackUtils.isEmpty(stack) && (stack.getItem() instanceof ItemBlock && (((ItemBlock) stack.getItem()).getBlock() instanceof BlockSapling) || Compatibility.isDynamicTreeSapling((sta
end of the line - double brackets not needed
brackets at all

2018-10-07 17:31 UTC, Nightenom commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java
> +import com.ferreusveritas.dynamictrees.blocks.BlockDynamicLeaves;
should be in compatibility files

2018-10-07 17:31 UTC, Nightenom commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java
> +    private static final String TAG_DYNAMIC_TREE = "dynamicTree";
-> nbt tags constants

2018-10-07 17:31 UTC, Nightenom commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/lumberjack/Tree.java
> +        if (Compatibility.isDynamicBlock(BlockPosUtil.getBlock(world, log))) {return;}
split into format described above

2018-10-07 17:31 UTC, Nightenom commented on src/api/java/com/minecolonies/api/compatibility/dynamicTrees/DynamicTreeProxy.java
> +     */
interesting parameter description, you can leave it empty if it's self-explaining, (I personally don't add them if it will be empty)

2018-10-07 17:32 UTC, marchermans requested changes

2018-10-07 17:32 UTC, OrionDevelopment commented on build.gradle
> +        url 'http://minecraft.curseforge.com/api/maven/'
No curseforge maven is not properly implemented. Untill they improve their implementation please find their official maven.

2018-10-07 22:54 UTC, LDTTeam-Buildsystem submitted a review, later dismissed
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

2018-10-08 02:37 UTC, LDTTeam-Buildsystem submitted a review, later dismissed
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

2018-10-08 02:50 UTC, LDTTeam-Buildsystem submitted a review, later dismissed
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

2018-10-08 12:17 UTC, LDTTeam-Buildsystem submitted a review, later dismissed
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

2018-10-08 12:48 UTC, LDTTeam-Buildsystem submitted a review, later dismissed
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

2018-10-08 15:24 UTC, LDTTeam-Buildsystem submitted a review, later dismissed
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

2018-10-25 18:12 UTC, closed without merging