Pathfinding fixes:
ldtteam/minecolonies pull request #3026
Opened 2018-10-30 15:12 UTC by someaddons

# Changes proposed in this pull request:

Pathfinding fixes:
-Capping deliveryman movementspeed increase
-Fixing various Movementpaths to not be recreated before the prev is completed
-Reducing Barbarian logic to 2 tps from 20, also reduces their path creation on each tick
-Introducing a cap to the amount of nodes the pathfinding can map, to reduce unnecessary calculations(e.g. prev stuck nodes:31000, new max:5000)

Review please

2018-10-30 15:18 UTC, Raycoms commented
Did you test that well?
Also in terms of getting people stuck on purpose to check if they recalculate the path accordingly as well.

2018-10-30 15:21 UTC, someaddons commented
ye tested it in singleplayer/smp and couldnt find any glitches/issues. For the ppl getting stuck: its the same as before, they just scan a smaller area(still pretty large) they're just acting as before

2018-10-30 15:32 UTC, Raycoms commented
Yeah in this case for getting stuck I meant where you "stopped the recalculation" while the path is in progress. Does this have any impact?

2018-10-30 15:43 UTC, someaddons commented
ah in that regard aside from performance it does affect the moveAway paths in the regard that they work better, moving away actually doesnt really work with constant refreshing, then the entitys do not really move.

2018-10-30 15:44 UTC, Raycoms commented
Ahh, sounds great.

2018-10-30 15:46 UTC, Raycoms commented
Ahh, sounds great.
Good finds, I never thought about checking these =)
:shipit:

2018-10-31 05:23 UTC, marchermans requested changes
Some small stuff.
Make the cap configurable.
Also some small Questions.

2018-10-31 05:23 UTC, marchermans commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java
> +            BASE_MOVEMENT_SPEED + (worker.getCitizenExperienceHandler().getLevel() > 50 ? 50 : worker.getCitizenExperienceHandler().getLevel()) * BONUS_SPEED_PER_LEVEL);
Nice this cap. But I would rather have this configurable please, in the sense that the config file specifies the max Level. Allows larger Servers to decrease this cap, to reduce load.

2018-10-31 05:23 UTC, marchermans commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> +                worker.getMoveHelper().strafe(0, 0);
Why is the strave inserted here?

2018-10-31 05:23 UTC, marchermans commented on src/main/java/com/minecolonies/coremod/entity/ai/mobs/barbarians/EntityAIAttackArcher.java
> +                final EntityTippedArrow arrowEntity = new EntityTippedArrow(CompatibilityUtils.getWorld(entity), entity);
Why not EntityArrow?

2018-10-31 07:55 UTC, ItsmeAga commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java
> +            BASE_MOVEMENT_SPEED + (worker.getCitizenExperienceHandler().getLevel() > 50 ? 50 : worker.getCitizenExperienceHandler().getLevel()) * BONUS_SPEED_PER_LEVEL);
ah good call thx!

2018-10-31 07:57 UTC, ItsmeAga commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> +                worker.getMoveHelper().strafe(0, 0);
because some of the guardAI's set strafing during the fight, so when the movement is reset I think it should be set to 0 aswell

2018-10-31 07:59 UTC, ItsmeAga commented on src/main/java/com/minecolonies/coremod/entity/ai/mobs/barbarians/EntityAIAttackArcher.java
> +                final EntityTippedArrow arrowEntity = new EntityTippedArrow(CompatibilityUtils.getWorld(entity), entity);
not sure, I just moved that code from beeing executed every tick to only execute when we're attack ready. Though I think one could use tipped arrows with some potion effects for difficulty scaling

2018-10-31 09:16 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/entity/ai/mobs/barbarians/EntityAIAttackArcher.java
> +                final EntityTippedArrow arrowEntity = new EntityTippedArrow(CompatibilityUtils.getWorld(entity), entity);
As far as I can tell this Code does not require EntityArrow. But @Raycoms might actually know more.

2018-10-31 09:23 UTC, someaddons commented on src/main/java/com/minecolonies/coremod/entity/ai/mobs/barbarians/EntityAIAttackArcher.java
> +                final EntityTippedArrow arrowEntity = new EntityTippedArrow(CompatibilityUtils.getWorld(entity), entity);
hm we're using the same for the guard AI aswell

2018-10-31 15:07 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/entity/ai/mobs/barbarians/EntityAIAttackArcher.java
> +                final EntityTippedArrow arrowEntity = new EntityTippedArrow(CompatibilityUtils.getWorld(entity), entity);
EntityArrow is abstract and can't be instantiated

2018-10-31 15:07 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/guard/AbstractEntityAIGuard.java
> +                worker.getMoveHelper().strafe(0, 0);
And yes, resetting strafing sounds good

2018-10-31 18:09 UTC, merged