Tavern
ldtteam/minecolonies pull request #4894
Opened 2020-05-05 14:54 UTC by someaddons

Closes #
Closes #
Closes #

# Changes proposed in this pull request:
-
-
-

Review please

2020-05-05 15:12 UTC, LDTTeam-Buildsystem commented
This PR has been automatically built and hosted by our build system, during this process there was a crash, error, or otherwise, please check on this at: https://teamcity.minecolonies.com/viewLog.html?buildId=39349&buildTypeId=LetSDevTogether_Minecolonies_PullRequests_2_DeployTestServer

2020-05-09 21:46 UTC, LDTTeam-Buildsystem commented
This PR has been automatically built and hosted by our build system, during this process there was a crash, error, or otherwise, please check on this at: https://teamcity.minecolonies.com/viewLog.html?buildId=39713&buildTypeId=LetSDevTogether_Minecolonies_PullRequests_2_DeployTestServer

2020-05-10 08:14 UTC, Raycoms commented on src/api/java/com/minecolonies/api/colony/buildings/ModBuildings.java
> +    public static BuildingEntry tavern;
this formatting looks wrong now =D

2020-05-10 08:20 UTC, Raycoms commented
:shipit:

2020-05-10 08:36 UTC, LDTTeam-Buildsystem commented
This PR has been automatically built and hosted by our build system, during this process there was a crash, error, or otherwise, please check on this at: https://teamcity.minecolonies.com/viewLog.html?buildId=39781&buildTypeId=LetSDevTogether_Minecolonies_PullRequests_2_DeployTestServer

2020-05-12 12:09 UTC, marchermans requested changes
This PR is a such to large.
Please refactor the PR into at least two separate pieces.

The actual addition of the tavern base building and its basic functionality should be one pr-
The additional changes required to make "hired" workers possible is another pr.
The adding of the "hired" workers is a third, if multiple types are required, then possibly even a forth or a fifth.

I understand from @Raycoms that you discussed this with him already, so if you do not think this is feasible I would be open to discuss stuff over discord.

2020-05-12 12:09 UTC, marchermans commented on src/api/java/com/minecolonies/api/IMinecoloniesAPI.java
> +    IForgeRegistry<CitizenDataRegistryEntry> getCitizenDataTypeRegistry();
It is either an `IForgeRegistry<CitizenDataTypeRegirtryEntry>` or the method should be called `getCitizenDataRegistry()`

2020-05-12 12:09 UTC, marchermans commented on src/api/java/com/minecolonies/api/MinecoloniesAPIProxy.java
> +    public IForgeRegistry<CitizenDataRegistryEntry> getCitizenDataTypeRegistry()
See interface declaration on naming issues.

2020-05-12 12:09 UTC, marchermans commented on src/api/java/com/minecolonies/api/colony/buildings/ModBuildings.java
> +    public static BuildingEntry tavern;
Yes please rerun the formatter.

2020-05-12 12:09 UTC, marchermans commented on src/api/java/com/minecolonies/api/colony/citizen/CitizenDataRegistryEntry.java
> +public class CitizenDataRegistryEntry extends ForgeRegistryEntry<CitizenDataRegistryEntry> implements IForgeRegistryEntry<CitizenDataRegistryEntry>
If I see this correctly, this would allow for a custom `ICitizenData` implementation to be used.
I do not think this is a good idea.

A better approach to solve this problem would be to make `ICitizenData` an `ICapabilityProvider` and via this way allow the handling and adaptation of custom data on a given citizen.

2020-05-12 12:09 UTC, marchermans commented on src/api/java/com/minecolonies/api/colony/citizen/CitizenDataRegistryEntry.java
> +public class CitizenDataRegistryEntry extends ForgeRegistryEntry<CitizenDataRegistryEntry> implements IForgeRegistryEntry<CitizenDataRegistryEntry>
Since i also see no real reason why this is part of this PR, it should be split of into a seperate one.

2020-05-12 12:09 UTC, marchermans commented on src/main/java/com/minecolonies/apiimp/initializer/ModCitizenDataTypeInitializer.java
> +        throw new IllegalStateException("Tried to initialize: CitizenDataInitializer but this is a Utility class.");
Your warning references the wrong class name: Should be: `ModCitizenDataTypeInitializer`?

2020-05-12 12:09 UTC, marchermans commented on src/main/java/com/minecolonies/coremod/colony/colonyEvents/ColonyRecruitableCitizenEvent.java
> +public class ColonyRecruitableCitizenEvent implements IColonyEntitySpawnEvent
Remove this class from this PR.
As stated it is not needed, can be added later again, but for now please do not mix feature and infrastructure or bugfixes in one PR but split them in several. 

Mixing the goals of a PR makes things harder.

2020-05-12 12:09 UTC, marchermans commented on src/main/java/com/minecolonies/coremod/colony/managers/BuildingManager.java
> +        if (block instanceof BlockHutWareHouse)
This needs to be way more dynamic.
I already told ray this.

Please find a way to make this more fluently useable.
Instead of doing a bunch of if switches design a registry or even a better placement logic system todo this.

2020-05-12 12:21 UTC, someaddons commented on src/main/java/com/minecolonies/coremod/colony/managers/BuildingManager.java
> +        if (block instanceof BlockHutWareHouse)
I think this would be too out of scope of this PR, I here just move the existing logic a bit

2020-05-12 12:42 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/colony/managers/BuildingManager.java
> +        if (block instanceof BlockHutWareHouse)
There are a lot of things in this PR that are completely out of scope...... Hence this PR needs to be broken up into several pieces.

2020-05-12 12:44 UTC, someaddons commented on src/main/java/com/minecolonies/coremod/colony/managers/BuildingManager.java
> +        if (block instanceof BlockHutWareHouse)
I wouldnt label 1 and an unused thing as a lot of things xD

2020-05-12 12:48 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/colony/managers/BuildingManager.java
> +        if (block instanceof BlockHutWareHouse)
1 and an unused thing is still 2 more then should be in this PR.

2020-05-12 12:49 UTC, OrionDevelopment commented on src/api/java/com/minecolonies/api/colony/citizen/CitizenDataRegistryEntry.java
> +public class CitizenDataRegistryEntry extends ForgeRegistryEntry<CitizenDataRegistryEntry> implements IForgeRegistryEntry<CitizenDataRegistryEntry>
Additionally I see no reason for it to exist at all..... So there is that, but i might be missing something.

2020-05-12 19:44 UTC, someaddons commented on src/api/java/com/minecolonies/api/colony/citizen/CitizenDataRegistryEntry.java
> +public class CitizenDataRegistryEntry extends ForgeRegistryEntry<CitizenDataRegistryEntry> implements IForgeRegistryEntry<CitizenDataRegistryEntry>
The idea for this was to have a central place for varying external citizen entities, which can be traders/visitor citizens/guards whatever and still get the sync benefit colonyviews serialization/deserialization.

2020-05-13 09:27 UTC, marchermans approved these changes

2020-05-13 10:39 UTC, Raycoms commented
:shipit:

2020-05-13 11:27 UTC, merged