Fixed sifter mesh buy option for creative mode.
ldtteam/minecolonies pull request #4926
Opened 2020-05-07 23:14 UTC by GeldornOfDragonhill

Also fixed the color setting of the labels.

Fixes the Problem in #4917 for the 1.15.2 version.

Review please

2020-05-07 23:21 UTC, Asherslab requested changes

2020-05-07 23:21 UTC, Asherslab commented on src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/sifter/SifterSettingsMessage.java
> +                InventoryUtils.reduceStackInItemHandler(new InvWrapper(player.inventory), mesh);
This is correct, however i just noticed that we don't check that the player (if in survival) has the item in their inventory on server side. As such this is exploitable (free upgrades) by a client using a bad version of the mod.

Can you please add a check up the top of this method to return if the player doesn't have the required item in their inventory (or ignore if in creative)

Thanks

2020-05-07 23:37 UTC, LDTTeam-Buildsystem commented
This PR has been automatically built and hosted by our build system, during this process there was a crash, error, or otherwise, please check on this at: https://teamcity.minecolonies.com/viewLog.html?buildId=39574&buildTypeId=LetSDevTogether_Minecolonies_PullRequests_2_DeployTestServer

2020-05-07 23:45 UTC, GeldornOfDragonhill commented
Added the server side check, should the player/log be notified of the error?
A quick check with the warehouse revealed a similar problem.

2020-05-07 23:48 UTC, Asherslab submitted a review, later dismissed

2020-05-08 00:07 UTC, LDTTeam-Buildsystem commented
This PR has been automatically built and hosted by our build system, during this process there was a crash, error, or otherwise, please check on this at: https://teamcity.minecolonies.com/viewLog.html?buildId=39577&buildTypeId=LetSDevTogether_Minecolonies_PullRequests_2_DeployTestServer

2020-05-08 07:21 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/network/messages/server/colony/building/sifter/SifterSettingsMessage.java
> +            if(!player.isCreative()) {
just need to fix the { formatting here

2020-05-08 19:15 UTC, GeldornOfDragonhill commented
Coding style fixes applied.

2020-05-08 19:41 UTC, LDTTeam-Buildsystem commented
This PR has been automatically built and hosted by our build system, during this process there was a crash, error, or otherwise, please check on this at: https://teamcity.minecolonies.com/viewLog.html?buildId=39633&buildTypeId=LetSDevTogether_Minecolonies_PullRequests_2_DeployTestServer

2020-05-09 08:29 UTC, merged