Feature/mechanist
ldtteam/minecolonies pull request #4933
Opened 2020-05-08 16:06 UTC by Raycoms

# Changes proposed in this pull request:
- Adds mechanic worker
- Improves some handling of requests of smelters
- Only allow overruling of requests that are assigned of the player (Rest is done via GUI still)

Review please

2020-05-08 16:20 UTC, marchermans requested changes
The RS Changes are okey, as per discussion.
However i would check your copy pasting work.....

2020-05-08 16:20 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/mechanic/EntityAIWorkMechanic.java
> +    public EntityAIWorkMechanic(@NotNull final JobMechanic sawmill)
Not a sawmill.

2020-05-08 16:43 UTC, LDTTeam-Buildsystem commented
This PR has been automatically built and hosted by our build system, during this process there was a crash, error, or otherwise, please check on this at: https://teamcity.minecolonies.com/viewLog.html?buildId=39595&buildTypeId=LetSDevTogether_Minecolonies_PullRequests_2_DeployTestServer

2020-05-08 19:22 UTC, LDTTeam-Buildsystem commented
This PR has been automatically built and hosted by our build system, during this process there was a crash, error, or otherwise, please check on this at: https://teamcity.minecolonies.com/viewLog.html?buildId=39617&buildTypeId=LetSDevTogether_Minecolonies_PullRequests_2_DeployTestServer

2020-05-09 08:18 UTC, someaddons approved these changes

2020-05-09 08:26 UTC, merged