Fixbuilderair
ldtteam/minecolonies pull request #517
Opened 2017-01-29 03:16 UTC by xavierh

Closes #457 

# Changes proposed in this pull request:
Sometimes the builder stop building waiting for an item he have in is chest and not on him.

This is because the builder have some AIR item in his inventory, while removing AIR item from the items needed, it will remove the first item, regardless to what it is,

This pr check for AIR item before removing it

The real question is, why <AIR Item>.isItemEqual(<any item>) is always true.

Review please

2017-01-29 11:03 UTC, marvin-bitterlich requested changes

2017-01-29 11:03 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java
> +        if (stack.getItemDamage()==0 && Item.getIdFromItem(stack.getItem()) == 0)
Use `neededItem.isEmpty()` for this

2017-01-29 11:52 UTC, forReason commented
Wow that was quite a struggle I guess. How did you find out?

2017-01-29 11:53 UTC, Kostronor commented
I wonder too, good find btw

2017-01-29 12:18 UTC, xavierh reviewed
It does not work with isEmpty. The stack is not empty it does have air in it

2017-01-29 12:18 UTC, xavierh commented on src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java
> +        if (stack.getItemDamage()==0 && Item.getIdFromItem(stack.getItem()) == 0)
Ok will try this and report back

2017-01-29 12:28 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java
> +        if (stack.getItemDamage()==0 && Item.getIdFromItem(stack.getItem()) == 0)
did you try with stack == Itemstack.EmptyStack
?

2017-01-29 13:25 UTC, xavierh commented
No, I will try.

I found by printing the list of needed items and the inventory in the sync
method. I noticed that when the problem occurred, the builder always had
air in his inventory.

Still does not explain why he's got air in the first place

On 29 Jan 2017 12:28, "Raycoms" <notifications@github.com> wrote:

*@Raycoms* commented on this pull request.
------------------------------

In src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java
<https://github.com/Minecolonies/minecolonies/pull/517>:

> @@ -288,6 +289,14 @@ public void addItemNeeded(@NotNull final ItemStack stack)
     public ItemStack removeItemNeeded(@NotNull final ItemStack stack)
     {
         @NotNull final ItemStack stackCopy = stack.copy();
+        //if stack is AIR, stack.isItemEqual(neededItem) will be always true
+        //and one itemNeeded would be remove
+        //There is probably a better way to check for air item
+        if (stack.getItemDamage()==0 &&
Item.getIdFromItem(stack.getItem()) == 0)

did you try with stack == Itemstack.EmptyStack
?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Minecolonies/minecolonies/pull/517>, or mute the thread
<https://github.com/notifications/unsubscribe-auth/ACplvG4cB76Ure_lBRy6TNsUxguKPfZxks5rXIXkgaJpZM4LwsLa>
.

2017-01-29 13:45 UTC, Raycoms commented
In 1.10 the inventory contained null stacks, in 1.11 they now contain air
stacks.

2017-01-29 11:25 GMT-02:00 xavierh <notifications@github.com>:

> No, I will try.
>
> I found by printing the list of needed items and the inventory in the sync
> method. I noticed that when the problem occurred, the builder always had
> air in his inventory.
>
> Still does not explain why he's got air in the first place
>
> On 29 Jan 2017 12:28, "Raycoms" <notifications@github.com> wrote:
>
> *@Raycoms* commented on this pull request.
> ------------------------------
>
> In src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java
> <https://github.com/Minecolonies/minecolonies/pull/517>:
>
> > @@ -288,6 +289,14 @@ public void addItemNeeded(@NotNull final ItemStack
> stack)
> public ItemStack removeItemNeeded(@NotNull final ItemStack stack)
> {
> @NotNull final ItemStack stackCopy = stack.copy();
> + //if stack is AIR, stack.isItemEqual(neededItem) will be always true
> + //and one itemNeeded would be remove
> + //There is probably a better way to check for air item
> + if (stack.getItemDamage()==0 &&
> Item.getIdFromItem(stack.getItem()) == 0)
>
> did you try with stack == Itemstack.EmptyStack
> ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Minecolonies/minecolonies/pull/517>, or mute the
> thread
> <https://github.com/notifications/unsubscribe-auth/ACplvG4cB76Ure_
> lBRy6TNsUxguKPfZxks5rXIXkgaJpZM4LwsLa>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Minecolonies/minecolonies/pull/517#issuecomment-275913575>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGI9y1jsgT8Tk250woYER4mm3jaSmSNnks5rXJM7gaJpZM4LwsLa>
> .
>

2017-01-29 16:14 UTC, xavierh commented
stack == ItemStack.EMPTY does not work neither as I suspected

2017-01-29 16:21 UTC, Raycoms commented
and check for stack == ItemStack.EMPTY || stack.getCount() == 0?

2017-01-29 14:14 GMT-02:00 xavierh <notifications@github.com>:

> stack == ItemStack.EMPTY does not work neither as I suspected
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Minecolonies/minecolonies/pull/517#issuecomment-275924373>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGI9yxPfOmCJasgN9JW37jI7Vd-9x01vks5rXLrkgaJpZM4LwsLa>
> .
>

2017-01-29 17:04 UTC, Kostronor commented
stack.isEmpty checks for null and == Stack.EMPTY, for Air, for <= 0 amount and for weird dmg values, so yeah that will work. If that does not work then there is something else wrong. I looked at the mc sources:

```
    public boolean isEmpty()
    {
        return this == EMPTY ? true : (this.item != null && this.item != Item.getItemFromBlock(Blocks.AIR) ? (this.stackSize <= 0 ? true : this.itemDamage < -32768 || this.itemDamage > 65535) : true);
    }
```

2017-01-29 17:04 UTC, xavierh commented
Noted, will test that

On 29 Jan 2017 16:21, "Raycoms" <notifications@github.com> wrote:

> and check for stack == ItemStack.EMPTY || stack.getCount() == 0?
>
> 2017-01-29 14:14 GMT-02:00 xavierh <notifications@github.com>:
>
> > stack == ItemStack.EMPTY does not work neither as I suspected
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/Minecolonies/minecolonies/pull/517#issuecomment-
> 275924373>,
> > or mute the thread
> > <https://github.com/notifications/unsubscribe-auth/
> AGI9yxPfOmCJasgN9JW37jI7Vd-9x01vks5rXLrkgaJpZM4LwsLa>
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Minecolonies/minecolonies/pull/517#issuecomment-275924856>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACplvHdVvMlcKgCk680gHHrjmx3FALTbks5rXLyLgaJpZM4LwsLa>
> .
>

2017-01-29 17:34 UTC, xavierh commented
> stack == ItemStack.EMPTY || stack.getCount() == 0

seems to work

2017-01-29 17:35 UTC, marvin-bitterlich commented
well that would stillt work with isEmpty xD

2017-01-29 18:16 UTC, xavierh commented
Yes you are right isEmpty should work. I did !stack.isEmpty by mistake :)

2017-01-30 11:09 UTC, xavierh commented
Ok, ready for review now

2017-01-30 11:44 UTC, marvin-bitterlich approved these changes

2017-01-30 13:28 UTC, merged