Adds gate blocks, for additional raid protection
ldtteam/minecolonies pull request #5727
Opened 2020-09-06 21:55 UTC by someaddons

# Changes proposed in this pull request:
This adds two gate blocks, one wooden one iron which are craftable by the mechanic.
Those have a max size of 5x4 and combine their hardness depending on size and act like vanilla doors, so that citizens and any other door using mechanic should work with them.

Fix raiders still using their old anti-stuck mechanics in addition to the new stuckhandler ones.
Fix herder trying to breed with one item.

Review please

2020-09-07 12:59 UTC, Raycoms commented
I'm not really happy having all the placement handlers in a different file, it was so easy to check and compare them in the old way =(

2020-09-07 13:01 UTC, someaddons commented
It was terrible to find and compare them in a single file :D

2020-09-07 13:02 UTC, Raycoms commented
they were all in a single location and all super small =P

2020-09-07 13:03 UTC, someaddons commented
multiple files = side by side comparison,  single file = stupid scrolling up and down all the time :D besides the IDe search doesnt find subclasses that well

2020-09-07 14:27 UTC, ravenbuilder934 requested changes

2020-09-07 14:27 UTC, ravenbuilder934 commented on src/main/resources/assets/minecolonies/lang/en_us.json
> +  "com.minecolonies.coremod.item.gate.place": "Autoplaces parts, max 5x4 which need a stack of 20",
```suggestion
  "com.minecolonies.coremod.item.gate.place": "Autoplaces parts. The max size is 5x4 which needs a stack of 20.",
```

2020-09-07 14:27 UTC, ravenbuilder934 commented on src/main/resources/assets/minecolonies/lang/en_us.json
> +  "com.minecolonies.coremod.item.gate.craft": "Crafted by the mechanic",
```suggestion
  "com.minecolonies.coremod.item.gate.craft": "Crafted by the Mechanic",
```

2020-09-09 05:11 UTC, OrionDevelopment approved these changes
I approve of the splitting of the handlers. Also nice addition!

2020-09-09 07:35 UTC, merged