Add nether supply ships
ldtteam/minecolonies pull request #5771
Opened 2020-09-13 07:06 UTC by ShadowProtocol

For AravanFox *et al.* builders

# Changes proposed in this pull request:
- Searches for schematics in ``nethership`` folders.
- Only netherships will work in the nether, and supplyships will only work in the overworld
- Netherships require a pool of lava to be placed in
- NOTE: not sure what the story is with the End, so I didn't really account for it.

Review please

2020-09-13 11:01 UTC, Raycoms commented
:shipit:

2020-09-13 15:14 UTC, ravenbuilder934 commented on src/main/resources/assets/minecolonies/lang/en_us.json
> +  "item.supplycampdeployer.invalid.lava_block_needed": "Placing a Supply Ship requires lava under the ship. These blocks must be lava: %s.",
```suggestion
  "item.supplycampdeployer.invalid.lava_block_needed": "Placing a Supply Ship in the Nether requires lava under the ship. These blocks must be lava: %s.",
```

2020-09-13 17:45 UTC, Mekle001 approved these changes, later dismissed

2020-09-14 10:01 UTC, OrionDevelopment requested changes
This looks in general to be okey.
We should however make a note to figure this out in a more general fashion.

2020-09-14 10:02 UTC, OrionDevelopment approved these changes
Request changes was wrong....
Wanted to approve.

2020-09-14 10:32 UTC, merged