Feature/#114 construction tape
ldtteam/minecolonies pull request #578
Opened 2017-02-11 18:06 UTC by nojo121

Closes #561 #572 

# Changes proposed in this pull request:
-fixed placing
-made it craftable
-made it breakable
-added config if builder should place it
-made it passable
-added name in lang file

Review please

2017-02-11 18:24 UTC, Raycoms commented
:shipit:  for me

2017-02-11 18:25 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/blocks/BlockConstructionTape.java
> +    public boolean isReplaceable(IBlockAccess worldIn, BlockPos pos)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Add the "@Override" annotation above this method signature [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1161)

2017-02-11 18:25 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/blocks/BlockConstructionTape.java
> +    public AxisAlignedBB getCollisionBoundingBox(IBlockState blockState, World worldIn, BlockPos pos)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Add the missing @deprecated Javadoc tag. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMissingDeprecatedCheck)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Add the "@Override" annotation above this method signature [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1161)
![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO') Do not forget to remove this deprecated code someday. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1133)

2017-02-11 18:25 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/blocks/BlockConstructionTapeCorner.java
> +    public boolean isReplaceable(IBlockAccess worldIn, BlockPos pos)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Add the "@Override" annotation above this method signature [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1161)

2017-02-11 18:25 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/blocks/BlockConstructionTapeCorner.java
> +    public AxisAlignedBB getCollisionBoundingBox(IBlockState blockState, World worldIn, BlockPos pos)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Add the missing @deprecated Javadoc tag. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMissingDeprecatedCheck)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Add the "@Override" annotation above this method signature [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1161)
![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO') Do not forget to remove this deprecated code someday. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1133)

2017-02-11 18:25 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/ConstructionTapeHelper.java
>      public static void placeConstructionTape(@NotNull WorkOrderBuild workOrder, @NotNull World world)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') The Cyclomatic Complexity of this method "placeConstructionTape" is 11 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

2017-02-11 18:25 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/util/RecipeHandler.java
> +        GameRegistry.addRecipe(new ItemStack(ModBlocks.blockConstructionTape, 16), "SWS", "S S", "S S", 'S', Items.STICK, 'W', new ItemStack(Blocks.WOOL, 1,4));
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Assign this magic number 4 to a well-named constant, and use the constant instead. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)

2017-02-11 18:25 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/configuration/ConfigurationHandler.java
> +            builderPlaceConstructionTape = config.get(CATEGORY_GAMEPLAY, "placeConstructionTape", builderPlaceConstructionTape, "Should builder place construction tape").getBoolean();
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Split this 183 characters long line (which is greater than 180 authorized). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS00103)

2017-02-11 18:25 UTC, MinecoloniesSonar commented
SonarQube analysis reported 12 issues
* ![MAJOR][MAJOR] 7 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 2 info

Watch the comments in this conversation to review them.

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-02-11 18:40 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/blocks/BlockConstructionTape.java
> +    public AxisAlignedBB getCollisionBoundingBox(IBlockState blockState, World worldIn, BlockPos pos)
![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO') Do not forget to remove this deprecated code someday. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1133)

2017-02-11 18:40 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/blocks/BlockConstructionTapeCorner.java
> +    public AxisAlignedBB getCollisionBoundingBox(IBlockState blockState, World worldIn, BlockPos pos)
![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO') Do not forget to remove this deprecated code someday. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS1133)

2017-02-11 18:40 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/util/RecipeHandler.java
> +          'S', Items.STICK, 'W', new ItemStack(Blocks.WOOL, 1,4));
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Assign this magic number 4 to a well-named constant, and use the constant instead. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)

2017-02-11 18:40 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/util/RecipeHandler.java
> +        GameRegistry.addRecipe(new ItemStack(ModBlocks.blockConstructionTape, 16), "SWS", "S S", "S S",
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)

2017-02-11 18:40 UTC, MinecoloniesSonar commented
SonarQube analysis reported 6 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 2 info

Watch the comments in this conversation to review them.

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-02-11 18:57 UTC, MinecoloniesSonar commented
SonarQube analysis reported 5 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 2 info

Watch the comments in this conversation to review them.

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-02-11 19:00 UTC, Raycoms commented
:shipit:

2017-02-12 10:52 UTC, marvin-bitterlich requested changes
Just some style remarks I would like to have fixed. Nothing mayor ;)

I'll do request changes so I can just hit approve once fixed

2017-02-12 10:52 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/ConstructionTapeHelper.java
> +                        {newY = newY-1;}
I'm sorry but this formats really weird :O
Can we change that to normal formatting?

2017-02-12 10:52 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java
> +                return block.getBlock() instanceof BlockDoor || block.getBlock() instanceof BlockFenceGate || block.getBlock() instanceof BlockConstructionTape
If you break it up, please break each || on a new line :)

2017-02-12 10:52 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/util/RecipeHandler.java
> +          'S', Items.STICK, 'W', new ItemStack(Blocks.WOOL, 1,4));
we should have here the color constant to spell what this number means as a color

2017-02-12 10:52 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java
> +            return SurfaceType.DROPABLE;
What does that mean? I am not in the code for that at the moment, sorry...

2017-02-12 11:07 UTC, nojo121 commented on src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java
> +            return SurfaceType.DROPABLE;
I don't know. Ask @Raycoms he edited the pathfinding.

2017-02-12 11:35 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java
> +            return SurfaceType.DROPABLE;
That means that they can't walk on top of it and they drop in.

2017-02-12 11:49 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java
> +                return block.getBlock() instanceof BlockDoor ||
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') '||' should be on a new line. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AOperator_Wrap)

2017-02-12 11:49 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java
> +                         block.getBlock() instanceof BlockFenceGate ||
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') '||' should be on a new line. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AOperator_Wrap)

2017-02-12 11:49 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/entity/pathfinding/AbstractPathJob.java
> +                         block.getBlock() instanceof BlockConstructionTape ||
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') '||' should be on a new line. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=checkstyle%3AOperator_Wrap)

2017-02-12 11:49 UTC, MinecoloniesSonar commented
SonarQube analysis reported 8 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 5 minor
* ![INFO][INFO] 2 info

Watch the comments in this conversation to review them.

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-02-12 12:18 UTC, marvin-bitterlich approved these changes

2017-02-12 12:18 UTC, merged

2017-02-12 12:27 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/util/RecipeHandler.java
> +    private static int     YELLOW_WOOL = 4;
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Rename this field "YELLOW_WOOL" to match the regular expression '^[a-z][a-zA-Z0-9]*$'. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS3008)
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Assign this magic number 4 to a well-named constant, and use the constant instead. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://home.kk-sc.de:9000/coding_rules#rule_key=squid%3AS109)

2017-02-12 12:27 UTC, MinecoloniesSonar commented
SonarQube analysis reported 6 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 2 info

Watch the comments in this conversation to review them.

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-02-13 14:16 UTC, pmardle commented
Good stuff guys :)