Fix #6048 and fix inventory detection issues
ldtteam/minecolonies pull request #6063
Opened 2020-11-10 20:36 UTC by Raycoms

Closes #6048
Closes #
Closes #

# Changes proposed in this pull request:
- Allows postbox to request enchanted books, potions and tipped arrows now
- Fix some inventory detection issues by using a set
- Use the more efficient building searching method

Review please

2020-11-10 20:40 UTC, someaddons approved these changes, later dismissed

2020-11-11 10:05 UTC, OrionDevelopment requested changes

2020-11-11 10:05 UTC, OrionDevelopment commented on src/api/java/com/minecolonies/api/compatibility/CompatibilityManager.java
>      }
This method is either named wrong, or does literally not what is written on the can.
Rename the method.

Also make this a parallel stream. With more then 1000+ entries in that list of items this should help.

2020-11-11 10:54 UTC, OrionDevelopment approved these changes

2020-11-11 11:22 UTC, someaddons approved these changes

2020-11-11 11:22 UTC, merged