Prune command
ldtteam/minecolonies pull request #6114
Opened 2020-11-19 13:40 UTC by someaddons

# Changes proposed in this pull request:
Adds a server utility prune world command, which will remove regions files which arent within a given range of a colony building. Useful to prune existing worlds, but keeping important colony places intact.

Review please

2020-11-19 13:45 UTC, Raycoms commented
Looks sound :shipit:

2020-11-19 14:02 UTC, ravenbuilder934 requested changes

2020-11-19 14:02 UTC, ravenbuilder934 commented on src/main/resources/assets/minecolonies/lang/en_us.json
> +  "com.minecolonies.command.prune.next": "This command will delete large chunks of your world! Use with care! Make a backup first! If you want to continue repeat this command with %d as first paramet
```suggestion
  "com.minecolonies.command.prune.next": "This command will delete large chunks of your world! Use with care! Make a backup first! If you want to continue, repeat this command with %d as the first parameter.",
```

2020-11-19 19:00 UTC, Mekle001 approved these changes
This looks good.

2020-11-19 19:07 UTC, Mekle001 commented
One thing that might be interesting in the future: A version of this that only works in the current world, or a specified world. I can see this being useful in many scenarios to only prune a single world.

2020-11-19 20:56 UTC, someaddons commented
> One thing that might be interesting in the future: A version of this that only works in the current world, or a specified world. I can see this being useful in many scenarios to only prune a single world.

ye I've been thinking about that aswell

2020-11-20 10:10 UTC, OrionDevelopment approved these changes

2020-11-20 10:12 UTC, merged