Add backup system for minecolonies.dat [#526]
ldtteam/minecolonies pull request #613
Opened 2017-02-16 15:19 UTC by asiekierka

Closes #526

# Changes proposed in this pull request:
- Adds backup system for minecolonies.dat as proposed in issue #526

Review please

2017-02-16 15:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Minecolonies/minecolonies?pullRequest=613) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Minecolonies/minecolonies?pullRequest=613) before we can accept your contribution.<br/>

2017-02-16 15:25 UTC, marvin-bitterlich requested changes
some minor things

2017-02-16 15:25 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/commands/BackupCommand.java
> +        return null;
this is marked notnull, return an empty list instead

2017-02-16 15:25 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/commands/BackupCommand.java
> +            if (ColonyManager.backupColonyData())
this should be done in the Server Thread I guess

2017-02-16 15:25 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/colony/ColonyManager.java
> +                backupColonyData();
the result is ignored. We should print out something, depending on if it worked or not

2017-02-16 15:37 UTC, asiekierka commented on src/main/java/com/minecolonies/coremod/commands/BackupCommand.java
> +            if (ColonyManager.backupColonyData())
Ah, yes, I forgot about RCON. sorry!

2017-02-17 07:22 UTC, Kostronor commented
:shipit: @Raycoms

2017-02-17 07:43 UTC, merged

2017-02-17 08:25 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/commands/BackupCommand.java
> +        if (!sender.canCommandSenderUseCommand(4, "minecolonies backup"))
@asiekierka We need this to be 3 it seems. There should be a constant somewhere in the commands hirarchy for that. I guess even a config option.

mc is weird xD