Bump structurize
ldtteam/minecolonies pull request #6810
Opened 2021-03-24 01:30 UTC by Raycoms

# Changes proposed in this pull request:
- Bump Structurize adjust gens etc
-
-

Review please

2021-03-24 01:55 UTC, ravenbuilder934 requested changes
Errors in the log:
`[20:50:06.618] [Render thread/ERROR] [TagCollectionReader/]: Couldn't load item tag minecolonies:sawmill_product as it is missing following references: #structurize:shingles (from main),#structurize:shingle_slabs (from main),#structurize:timber_frames (from main) 
[20:50:06.618] [Render thread/ERROR] [TagCollectionReader/]: Couldn't load item tag minecolonies:blacksmith_product_excluded as it is missing following references: #minecolonies:sawmill_product (from main) 
[20:53:04.002] [Render thread/ERROR] [TagCollectionReader/]: Couldn't load block tag minecolonies:pathblocks as it is missing following references: structurize:blockcreambricks (from main),structurize:blockbrownbricks (from main),structurize:blockbeigebricks (from main),structurize:blockcreambrickstairs (from main),structurize:blockbrownbrickstairs (from main),structurize:blockbeigebrickstairs (from main),structurize:blockcreambrickslab (from main),structurize:blockbrownbrickslab (from main),structurize:blockbeigebrickslab (from main)`

2021-03-24 02:02 UTC, Mekle001 approved these changes, later dismissed

2021-03-24 02:22 UTC, ravenbuilder934 approved these changes, later dismissed

2021-03-24 02:23 UTC, Mekle001 approved these changes, later dismissed

2021-04-03 13:57 UTC, ravenbuilder934 commented
Waiting on https://github.com/ldtteam/Structurize/pull/338

2021-04-04 16:57 UTC, merged