Add correct handling of resolver cancellation
ldtteam/minecolonies pull request #7101
Opened 2021-05-15 00:31 UTC by Raycoms

# Changes proposed in this pull request:
- Fixes an issue when removing a crafter building would cause RS issues.
-
-

Review please

2021-05-15 12:20 UTC, OrionDevelopment requested changes

2021-05-15 12:20 UTC, OrionDevelopment commented on src/api/java/com/minecolonies/api/colony/requestsystem/management/IRequestHandler.java
> +    void removeFromTempBlackList(IToken<?> resolverToken);
This needs to be in the resolver handler.
This has intrinsically more todo with resolvers and not so much with requests.

2021-05-15 13:51 UTC, someaddons approved these changes

2021-05-16 07:08 UTC, OrionDevelopment approved these changes
This looks good now.

2021-05-16 23:38 UTC, merged