Add hint to beekeeper no hive message
ldtteam/minecolonies pull request #7124
Opened 2021-05-20 06:02 UTC by dhouck

It's not obvious what to do when there's no hive for the beekeeper to work at, so explain that the hive tool is needed.

Closes #
Closes #
Closes #

# Changes proposed in this pull request:
-
-
-

Review please

2021-05-20 07:17 UTC, OrionDevelopment approved these changes, later dismissed

2021-05-20 17:31 UTC, ravenbuilder934 requested changes

2021-05-20 17:31 UTC, ravenbuilder934 commented on src/main/resources/assets/minecolonies/lang/en_us.json
> +  "entity.beekeeper.messagenohives": "There are no hives for me to work at!  Please assign me some using the hive tool available from my hut.",
```suggestion
  "entity.beekeeper.messagenohives": "Either there are no hives for me to work at, or you haven't assigned me any. Use the hive tool available from my hut to assign hives.",
```

2021-05-20 17:34 UTC, Raycoms commented on src/main/resources/assets/minecolonies/lang/en_us.json
> +  "entity.beekeeper.messagenohives": "There are no hives for me to work at!  Please assign me some using the hive tool available from my hut.",
Use the hive tool available from my hut to do so. ? else it sounds repetitive

2021-05-20 17:35 UTC, ravenbuilder934 commented on src/main/resources/assets/minecolonies/lang/en_us.json
> +  "entity.beekeeper.messagenohives": "There are no hives for me to work at!  Please assign me some using the hive tool available from my hut.",
Good point

2021-05-20 20:23 UTC, dhouck commented
Yeah, the suggested wording changes were good; updated

2021-05-20 21:12 UTC, ravenbuilder934 approved these changes

2021-05-21 02:47 UTC, Mekle001 approved these changes

2021-05-21 08:29 UTC, OrionDevelopment approved these changes

2021-05-21 11:12 UTC, merged