Amazon Spearman and Spear Weapon
ldtteam/minecolonies pull request #7710
Opened 2021-10-24 09:38 UTC by TagnumElite

I have created an Amazon Spearman as well as a Spear item that acts just like a trident, just with out riptide.

# Changes proposed in this pull request:
- Add Amazon Spearman Entity
- Add Spear Weapon
- Allow ranged mobs to also shoot spears and tridents

Review please
The Spear:
![spear pictures](https://user-images.githubusercontent.com/6497721/138592847-7a1284b9-6b69-48d3-84b1-d0bc878d92f8.png)
The Amazon Spearman (is a link to a video)
[![amazon pictures](https://user-images.githubusercontent.com/6497721/138761061-84ddc850-d6ce-4e1e-9864-0acc6a45f654.png)](https://youtu.be/nXfafa6Er64)

2021-10-24 10:10 UTC, Raycoms commented
Can we have some images?

2021-10-24 10:12 UTC, Raycoms commented on src/api/java/com/minecolonies/api/entity/SpearEntity.java
> +        if (this.inGroundTime > 4)
Does all of this here have to happen every tick?

2021-10-24 10:12 UTC, Raycoms commented on src/api/java/com/minecolonies/api/entity/SpearEntity.java
> +            else if (i > 0)
What is i?

2021-10-24 10:13 UTC, Raycoms commented on src/api/java/com/minecolonies/api/entity/SpearEntity.java
> +        this.setDeltaMovement(this.getDeltaMovement().multiply(-0.01D, -0.1D, -0.01D));
I think we don't need the thundering bonus here. Doesn't fit the amazons too well.

2021-10-24 10:14 UTC, Raycoms commented on src/api/java/com/minecolonies/api/entity/mobs/RaiderMobUtils.java
> +        }
formatting

2021-10-24 10:15 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/client/render/projectile/RendererSpear.java
> +    public RendererSpear(EntityRendererManager entityRendererManager) {
formatting

2021-10-24 10:16 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/colony/colonyEvents/raidEvents/amazonevent/AmazonRaidEvent.java
> -    @Override
I don't think you should remove those two methods

2021-10-24 11:14 UTC, marchermans requested changes
Generally a good start.
I agree with Ray that some code likely does not need to run every tick on the spear entity.
And some clean up needs to be done before this is ready.

But all in all a good start

2021-10-24 11:14 UTC, marchermans commented on src/main/java/com/minecolonies/coremod/entity/ai/registry/MobAIRegistry.java
> +          .registerNewStateAI(mob -> new RaiderRangedAI<>(mob, mob.getAI()), mob -> mob instanceof IArcherMobEntity || mob instanceof ISpearmanMobEntity)
Should be collapsed into a single super interface: `IRangedAttackEntity` instead of having two different interfaces for this.

2021-10-24 11:14 UTC, marchermans commented on src/main/java/com/minecolonies/coremod/items/ItemSpear.java
> +    public static class SpearTileRenderer extends ItemStackTileEntityRenderer
Please do not mix client code in inner classes.
This is a disaster waiting to happen on servers.

Extract this class and move it to the correct client package.

2021-10-24 11:30 UTC, TagnumElite commented
Yeah, thats why I left this as a draft pr. I am using the trident as a reference, but I was thinking. The spear doesn't need the loyal enchant, just has to be generic right?

2021-10-24 11:58 UTC, TagnumElite commented on src/main/java/com/minecolonies/coremod/colony/colonyEvents/raidEvents/amazonevent/AmazonRaidEvent.java
> -    @Override
The were overridden because there was no normal raider type for amazons. I have set the normal mob type to spearmen, therefore these overrides are no longer needed.

2021-10-24 11:59 UTC, TagnumElite commented on src/main/java/com/minecolonies/coremod/entity/ai/registry/MobAIRegistry.java
> +          .registerNewStateAI(mob -> new RaiderRangedAI<>(mob, mob.getAI()), mob -> mob instanceof IArcherMobEntity || mob instanceof ISpearmanMobEntity)
Will do

2021-10-24 11:59 UTC, TagnumElite commented on src/main/java/com/minecolonies/coremod/items/ItemSpear.java
> +    public static class SpearTileRenderer extends ItemStackTileEntityRenderer
Yeah, will do.

2021-10-24 21:25 UTC, Raycoms commented
> Can we have some images?

Also one of the spearman model?

2021-10-24 21:25 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/colony/colonyEvents/raidEvents/amazonevent/AmazonRaidEvent.java
> -    @Override
ah okay,

2021-10-25 14:52 UTC, TagnumElite commented
I duplicated the normal amazon model. Will be making a new model today.

2021-10-25 14:58 UTC, Raycoms commented
> I duplicated the normal amazon model. Will be making a new model today.

For me using the current archer model is totally fine, I'd just slightly adjust the skin a bit.

2021-10-26 18:50 UTC, TagnumElite commented
I believe that is everything, only thing I dislike right now is the spear item texture. I'm not an artist.

2021-11-22 11:00 UTC, Raycoms commented
@TagnumElite is this ready for review? You need to remove the not ready tag then?

2021-11-24 16:36 UTC, TagnumElite commented
I am unable to edit tags, which is why I sent the message.

2021-11-28 11:33 UTC, OrionDevelopment approved these changes, later dismissed

2021-11-28 12:56 UTC, someaddons reviewed
Looks good, just some doc/comments left

2021-11-28 12:56 UTC, someaddons commented on src/api/java/com/minecolonies/api/entity/SpearEntity.java
> +public class SpearEntity extends AbstractArrowEntity implements ICustomAttackSound
missing javadoc on class and vars

2021-11-28 12:56 UTC, someaddons commented on src/api/java/com/minecolonies/api/entity/SpearEntity.java
> +public class SpearEntity extends AbstractArrowEntity implements ICustomAttackSound
The projectile should get a limited lifetime similar to our existing CustomArrowEntity, to make sure it'll despawn, even if it never hits the ground

2021-11-28 12:56 UTC, someaddons commented on src/api/java/com/minecolonies/api/entity/mobs/amazons/IAmazonSpearman.java
> +public interface IAmazonSpearman extends IAmazonEntity, ISpearmanMobEntity
javadoc missing

2021-11-28 12:56 UTC, someaddons commented on src/main/java/com/minecolonies/coremod/client/model/ModelSpear.java
> +public class ModelSpear extends Model
javadoc missing in this class

2021-11-28 22:25 UTC, someaddons approved these changes, later dismissed

2022-02-06 13:49 UTC, someaddons approved these changes

2022-02-06 13:59 UTC, merged