Some fixes
ldtteam/minecolonies pull request #7770
Opened 2021-11-14 14:33 UTC by someaddons

# Changes proposed in this pull request:
Fix block search Util not advancing Y levels correctly
Fix racks to update to their newer rotations

Review please

2021-11-14 22:46 UTC, Raycoms approved these changes

2021-11-14 22:48 UTC, Mekle001 requested changes

2021-11-14 22:48 UTC, Mekle001 commented on src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java
> +            updateBlockState();
Shouldn't we be updating the version here? It seems like it will always be zero and do this every time.

2021-11-14 22:50 UTC, Raycoms requested changes

2021-11-14 22:50 UTC, Raycoms commented on src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java
> +            updateBlockState();
yep

2021-11-14 23:03 UTC, someaddons commented on src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java
> +            updateBlockState();
indeed, good catch

2021-11-15 04:59 UTC, Mekle001 approved these changes

2021-11-15 07:01 UTC, uecasm commented on src/api/java/com/minecolonies/api/tileentities/TileEntityRack.java
> +            updateBlockState();
It'll also do it again on version 2->3, although I suppose the code can be changed when that actually happens to fix it then...

2021-11-16 13:54 UTC, merged