issue template update
ldtteam/minecolonies pull request #8088
Opened 2022-02-22 13:39 UTC by Raycoms

# Changes proposed in this pull request:
- Update the issue
-
-

Review please

2022-02-22 16:31 UTC, Nightenom requested changes
also the second one :D

2022-02-22 18:24 UTC, Raycoms commented
I would delete #3, I will update #2

2022-02-22 20:30 UTC, uecasm commented on .github/ISSUE_TEMPLATE/10-bug-report.yaml
> +        - label: I checked the MineColonie Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.
still

2022-02-22 23:35 UTC, Raycoms commented on .github/ISSUE_TEMPLATE/10-bug-report.yaml
> +        - label: I checked the MineColonie Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.
What here?

2022-02-23 04:30 UTC, uecasm commented on .github/ISSUE_TEMPLATE/10-bug-report.yaml
> +        - label: I checked the MineColonie Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.
"Minecolonie", like I mentioned on discord

2022-02-24 15:51 UTC, merged