Feature/#746 free block tool
ldtteam/minecolonies pull request #813
Opened 2017-04-16 11:32 UTC by Isfirs

Closes #746

2017-04-16 15:33 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/network/messages/ChangeFreeToInteractBlockMessage.java
>              {
Ouch, nice catch.

2017-04-16 15:34 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        ColonyView colonyView = ColonyManager.getClosestColonyView(worldIn, pos);
add final

2017-04-16 15:34 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        String tagItemMode = compound.getString(TAG_ITEM_MODE);
add final

2017-04-16 15:35 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        String tagItemMode = compound.getString(TAG_ITEM_MODE);
also final to the method params please

2017-04-16 15:35 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        ColonyView colonyView = ColonyManager.getClosestColonyView(worldIn, pos);
also final to the method params please

2017-04-16 15:35 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        String itemMode = compound.getString(TAG_ITEM_MODE);
final everywhere

2017-04-16 15:35 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        String itemMode = compound.getString(TAG_ITEM_MODE);
and I think it should be private static void

2017-04-16 15:35 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        IBlockState blockState = worldIn.getBlockState(pos);
some finals around here as well and private static

2017-04-16 15:36 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        ChangeFreeToInteractBlockMessage message = new ChangeFreeToInteractBlockMessage(colonyView, pos, ChangeFreeToInteractBlockMessage.MessageType.ADD_BLOCK);
finals and private static

2017-04-16 15:36 UTC, Raycoms commented
Seems overally good, only some small style issues.

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ModItems.java
>      public static final Item supplyChest  = new ItemSupplyChestDeployer();
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +    static private EnumActionResult handleAddBlockType(
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Reorder the modifiers to comply with the Java Language Specification. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AModifiersOrderCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        String tagItemMode = compound.getString(TAG_ITEM_MODE);
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 5. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        super("scepterPermission");
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 5. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        switch(tagItemMode) {
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Move this left curly brace to the beginning of next line of code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        if (!scepter.hasTagCompound())
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 5. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +                return handleAddBlockType(playerIn, worldIn, pos, colonyView);
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 9. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +            scepter.setTagCompound(new NBTTagCompound());
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 7. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        IBlockState blockState = worldIn.getBlockState(pos);
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 5. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +                return handleAddLocation(playerIn, worldIn, pos, colonyView);
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 9. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        final NBTTagCompound compound = scepter.getTagCompound();
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Move the declaration of "compound" closer to the code that uses it. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1941)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        if (worldIn.isRemote)
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 5. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +                toggleItemMode(playerIn, compound);
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 9. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +            return new ActionResult(EnumActionResult.PASS, scepter);
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 7. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +            return EnumActionResult.SUCCESS;
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 7. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +    static private void toggleItemMode(EntityPlayer playerIn, NBTTagCompound compound)
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Reorder the modifiers to comply with the Java Language Specification. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AModifiersOrderCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +            scepter.setTagCompound(new NBTTagCompound());
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 7. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        String itemMode = compound.getString(TAG_ITEM_MODE);
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 5. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +            return EnumActionResult.FAIL;
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 7. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +    static private EnumActionResult handleAddLocation(
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Reorder the modifiers to comply with the Java Language Specification. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AModifiersOrderCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +            case TAG_VALUE_MODE_BLOCK:
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') End this switch case with an unconditional break, return or throw statement. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS128)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +                compound.setString(TAG_ITEM_MODE, TAG_VALUE_MODE_LOCATION);
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 9. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +    private static final String TAG_ITEM_MODE = "scepterMode";
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 3. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        ChangeFreeToInteractBlockMessage message = new ChangeFreeToInteractBlockMessage(colonyView, pos, ChangeFreeToInteractBlockMessage.MessageType.ADD_BLOCK);
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 5. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +                compound.setString(TAG_ITEM_MODE, TAG_VALUE_MODE_BLOCK);
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 9. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:05 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/network/messages/ChangeFreeToInteractBlockMessage.java
> +                    colony.removeFreePosition(message.pos);
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 11. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:06 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/network/messages/ChangeFreeToInteractBlockMessage.java
> +                    colony.addFreeBlock(message.block);
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 11. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:06 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/network/messages/ChangeFreeToInteractBlockMessage.java
> +                    colony.addFreePosition(message.pos);
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 11. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:06 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/network/messages/ChangeFreeToInteractBlockMessage.java
>                  if (!(message.pos.getX() == 0 && message.pos.getZ() == 0 && message.pos.getY() == 0))
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 9. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:06 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/network/messages/ChangeFreeToInteractBlockMessage.java
> +                    colony.removeFreeBlock(message.block);
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 11. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:06 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/network/messages/ChangeFreeToInteractBlockMessage.java
>                  if (!(message.pos.getX() == 0 && message.pos.getZ() == 0 && message.pos.getY() == 0))
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Make this line start at column 9. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-04-18 09:06 UTC, MinecoloniesSonar commented
SonarQube analysis reported 141 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 135 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [ChangeFreeToInteractBlockMessage.java#L114](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/network/messages/ChangeFreeToInteractBlockMessage.java#L114): Refactor this method to reduce its Cognitive Complexity from 16 to the 15 allowed. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![CRITICAL][CRITICAL] [ColonyPermissionEventHandler.java#L198](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L198): The Cyclomatic Complexity of this method "on" is 21 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![CRITICAL][CRITICAL] [ColonyPermissionEventHandler.java#L198](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L198): Refactor this method to reduce its Cognitive Complexity from 31 to the 15 allowed. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [ModItems.java#L24](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/items/ModItems.java#L24): This block of commented-out lines of code should be removed. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [ColonyPermissionEventHandler.java#L38](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L38): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 34 to the maximum authorized 20 or less. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-04-18 09:12 UTC, MinecoloniesSonar commented
SonarQube analysis reported 52 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 46 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [ChangeFreeToInteractBlockMessage.java#L114](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/network/messages/ChangeFreeToInteractBlockMessage.java#L114): Refactor this method to reduce its Cognitive Complexity from 16 to the 15 allowed. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![CRITICAL][CRITICAL] [ColonyPermissionEventHandler.java#L198](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L198): The Cyclomatic Complexity of this method "on" is 21 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![CRITICAL][CRITICAL] [ColonyPermissionEventHandler.java#L198](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L198): Refactor this method to reduce its Cognitive Complexity from 31 to the 15 allowed. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [ModItems.java#L24](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/items/ModItems.java#L24): This block of commented-out lines of code should be removed. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [ColonyPermissionEventHandler.java#L38](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L38): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 34 to the maximum authorized 20 or less. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-04-18 09:42 UTC, MinecoloniesSonar commented
SonarQube analysis reported 51 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 46 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [ColonyPermissionEventHandler.java#L198](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L198): The Cyclomatic Complexity of this method "on" is 21 which is greater than 15 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![CRITICAL][CRITICAL] [ColonyPermissionEventHandler.java#L198](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L198): Refactor this method to reduce its Cognitive Complexity from 31 to the 20 allowed. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [ModItems.java#L24](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/items/ModItems.java#L24): This block of commented-out lines of code should be removed. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [ColonyPermissionEventHandler.java#L38](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L38): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 34 to the maximum authorized 20 or less. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/d35e31a1591dba369e504e109ffb1b3fc632f54b/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-04-18 16:04 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +        if (worldIn.isRemote) {
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Move this left curly brace to the beginning of next line of code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

2017-04-18 16:04 UTC, MinecoloniesSonar commented
SonarQube analysis reported 46 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 42 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [ColonyPermissionEventHandler.java#L198](https://github.com/Minecolonies/minecolonies/blob/1d923930786a842760dd6e676e47243929446808/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L198): The Cyclomatic Complexity of this method "on" is 21 which is greater than 15 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![CRITICAL][CRITICAL] [ColonyPermissionEventHandler.java#L198](https://github.com/Minecolonies/minecolonies/blob/1d923930786a842760dd6e676e47243929446808/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L198): Refactor this method to reduce its Cognitive Complexity from 31 to the 20 allowed. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [ModItems.java#L24](https://github.com/Minecolonies/minecolonies/blob/1d923930786a842760dd6e676e47243929446808/src/main/java/com/minecolonies/coremod/items/ModItems.java#L24): This block of commented-out lines of code should be removed. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [ColonyPermissionEventHandler.java#L38](https://github.com/Minecolonies/minecolonies/blob/1d923930786a842760dd6e676e47243929446808/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L38): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 34 to the maximum authorized 20 or less. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/1d923930786a842760dd6e676e47243929446808/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/1d923930786a842760dd6e676e47243929446808/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/1d923930786a842760dd6e676e47243929446808/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/1d923930786a842760dd6e676e47243929446808/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/1d923930786a842760dd6e676e47243929446808/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/1d923930786a842760dd6e676e47243929446808/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-04-18 16:12 UTC, MinecoloniesSonar commented
SonarQube analysis reported 45 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 41 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [ColonyPermissionEventHandler.java#L198](https://github.com/Minecolonies/minecolonies/blob/dbb9149e1dcda3d3925325e66f5710a838a36c15/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L198): The Cyclomatic Complexity of this method "on" is 21 which is greater than 15 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![CRITICAL][CRITICAL] [ColonyPermissionEventHandler.java#L198](https://github.com/Minecolonies/minecolonies/blob/dbb9149e1dcda3d3925325e66f5710a838a36c15/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L198): Refactor this method to reduce its Cognitive Complexity from 31 to the 20 allowed. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [ModItems.java#L24](https://github.com/Minecolonies/minecolonies/blob/dbb9149e1dcda3d3925325e66f5710a838a36c15/src/main/java/com/minecolonies/coremod/items/ModItems.java#L24): This block of commented-out lines of code should be removed. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [ColonyPermissionEventHandler.java#L38](https://github.com/Minecolonies/minecolonies/blob/dbb9149e1dcda3d3925325e66f5710a838a36c15/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L38): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 34 to the maximum authorized 20 or less. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/dbb9149e1dcda3d3925325e66f5710a838a36c15/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/dbb9149e1dcda3d3925325e66f5710a838a36c15/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/dbb9149e1dcda3d3925325e66f5710a838a36c15/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/dbb9149e1dcda3d3925325e66f5710a838a36c15/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/dbb9149e1dcda3d3925325e66f5710a838a36c15/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/dbb9149e1dcda3d3925325e66f5710a838a36c15/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-04-18 16:47 UTC, marvin-bitterlich requested changes
please fix the javadoc 😉

2017-04-18 16:47 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +     */
wtf javadoc?

2017-04-18 16:47 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/items/ItemScepterPermission.java
> +    /**
here too real javadoc pls

2017-04-18 20:40 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java
> +                if (cancel) {
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Move this left curly brace to the beginning of next line of code. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3ALeftCurlyBraceStartLineCheck)

2017-04-18 20:40 UTC, MinecoloniesSonar commented
SonarQube analysis reported 46 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 43 minor

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ColonyPermissionEventHandler.java#L39](https://github.com/Minecolonies/minecolonies/blob/7b3535336b4f0fe09f6a1832c85ebbf7b6516d99/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L39): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 35 to the maximum authorized 20 or less. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [ColonyPermissionEventHandler.java#L199](https://github.com/Minecolonies/minecolonies/blob/7b3535336b4f0fe09f6a1832c85ebbf7b6516d99/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L199): The Cyclomatic Complexity of this method "on" is 23 which is greater than 15 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [ColonyPermissionEventHandler.java#L199](https://github.com/Minecolonies/minecolonies/blob/7b3535336b4f0fe09f6a1832c85ebbf7b6516d99/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L199): Refactor this method to reduce its Cognitive Complexity from 34 to the 20 allowed. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/7b3535336b4f0fe09f6a1832c85ebbf7b6516d99/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/7b3535336b4f0fe09f6a1832c85ebbf7b6516d99/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/7b3535336b4f0fe09f6a1832c85ebbf7b6516d99/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/7b3535336b4f0fe09f6a1832c85ebbf7b6516d99/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/7b3535336b4f0fe09f6a1832c85ebbf7b6516d99/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/7b3535336b4f0fe09f6a1832c85ebbf7b6516d99/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/7b3535336b4f0fe09f6a1832c85ebbf7b6516d99/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-04-18 20:53 UTC, MinecoloniesSonar commented
SonarQube analysis reported 45 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 42 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ColonyPermissionEventHandler.java#L39](https://github.com/Minecolonies/minecolonies/blob/e61b982ce5aa51475ef7136c869ba3ddbf29737b/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L39): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 35 to the maximum authorized 20 or less. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [ColonyPermissionEventHandler.java#L199](https://github.com/Minecolonies/minecolonies/blob/e61b982ce5aa51475ef7136c869ba3ddbf29737b/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L199): The Cyclomatic Complexity of this method "on" is 23 which is greater than 15 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [ColonyPermissionEventHandler.java#L199](https://github.com/Minecolonies/minecolonies/blob/e61b982ce5aa51475ef7136c869ba3ddbf29737b/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L199): Refactor this method to reduce its Cognitive Complexity from 34 to the 20 allowed. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/e61b982ce5aa51475ef7136c869ba3ddbf29737b/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/e61b982ce5aa51475ef7136c869ba3ddbf29737b/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/e61b982ce5aa51475ef7136c869ba3ddbf29737b/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/e61b982ce5aa51475ef7136c869ba3ddbf29737b/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/e61b982ce5aa51475ef7136c869ba3ddbf29737b/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/e61b982ce5aa51475ef7136c869ba3ddbf29737b/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/e61b982ce5aa51475ef7136c869ba3ddbf29737b/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-04-19 16:59 UTC, MinecoloniesSonar commented
SonarQube analysis reported 45 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 42 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ColonyPermissionEventHandler.java#L39](https://github.com/Minecolonies/minecolonies/blob/4281d42ecf297467602c39ce394d31059c0fc5a1/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L39): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 35 to the maximum authorized 20 or less. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [ColonyPermissionEventHandler.java#L199](https://github.com/Minecolonies/minecolonies/blob/4281d42ecf297467602c39ce394d31059c0fc5a1/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L199): The Cyclomatic Complexity of this method "on" is 22 which is greater than 15 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [ColonyPermissionEventHandler.java#L199](https://github.com/Minecolonies/minecolonies/blob/4281d42ecf297467602c39ce394d31059c0fc5a1/src/main/java/com/minecolonies/coremod/permissions/ColonyPermissionEventHandler.java#L199): Refactor this method to reduce its Cognitive Complexity from 31 to the 20 allowed. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/4281d42ecf297467602c39ce394d31059c0fc5a1/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/4281d42ecf297467602c39ce394d31059c0fc5a1/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/4281d42ecf297467602c39ce394d31059c0fc5a1/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/4281d42ecf297467602c39ce394d31059c0fc5a1/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/4281d42ecf297467602c39ce394d31059c0fc5a1/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/4281d42ecf297467602c39ce394d31059c0fc5a1/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/4281d42ecf297467602c39ce394d31059c0fc5a1/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-04-23 07:10 UTC, marvin-bitterlich approved these changes

2017-04-23 07:10 UTC, Kostronor commented
:shipit: @Raycoms

2017-04-23 12:06 UTC, Raycoms commented
:shipit:

2017-04-23 12:06 UTC, merged