Fix being able to select non builders hut using resource scroll
ldtteam/minecolonies pull request #8184
Opened 2022-03-25 11:45 UTC by Thodor12

Closes ldtteam/minecolonies-features#407
Closes #
Closes #

# Changes proposed in this pull request:
- Prevents players from linking a resource scroll to non builders hut buildings, change would include one new translation message to be added

Review please

(First PR, should I make multiple PR's to fix this identical issue on other versions or how does the process go?)

2022-03-25 11:51 UTC, Raycoms requested changes
Just a small formatting problem

2022-03-25 11:51 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/items/ItemResourceScroll.java
> +            if (buildingEntity.getBuilding() instanceof BuildingBuilder) {
Please adjust the formatting to fit our style. You can find a formatting file in the documentation folder in the REPO.
Manual formatting would be then

{


}

2022-03-25 11:51 UTC, Raycoms commented
I'll port it over to the other versions myself through some cherrypicks

2022-03-25 11:57 UTC, Thodor12 commented
Regarding the TODO about the building names, is this proper name available somewhere?
I checked throughout the building entity and building class but the best I could find was the schematic name.

2022-03-25 11:59 UTC, OrionDevelopment submitted a review, later dismissed

2022-03-25 12:01 UTC, Raycoms commented
> Regarding the TODO about the building names, is this proper name available somewhere? I checked throughout the building entity and building class but the best I could find was the schematic name.

The building entry got a translation key.

2022-03-27 10:17 UTC, OrionDevelopment approved these changes

2022-03-27 17:27 UTC, merged