Update BlockPosUtil.java
ldtteam/minecolonies pull request #8376
Opened 2022-05-15 17:22 UTC by Thodor12

# Changes proposed in this pull request:
- Remove unknown check

Review please

2022-05-15 17:26 UTC, Nightenom requested changes
The method can still return null if pos.xz = building.xz

2022-05-15 17:29 UTC, Thodor12 commented
What scenario should xz return, since this is only possible to reproduce when placed directly above the hut block.
I don't think an empty string is a great idea

2022-05-15 17:32 UTC, MotionlessTrain commented
If pos is within one block of the building, it is also returning null
(e.g. `pos.getX() == building.getX() && pos.getZ() == building.getZ()`)
Maybe a default value of a text component of an empty string is better, or an ">=" check could help as well for this specific case

2022-05-15 17:33 UTC, Thodor12 commented
> If pos is within one block of the building, it is also returning null (e.g. `pos.getX() == building.getX() && pos.getZ() == building.getZ()`) Maybe a default value of a text component of an empty string is better, or an ">=" check could help as well for this specific case

Talking to Ray, am already gonna remove the +1 on either side as these aren't really needed

2022-05-15 17:35 UTC, Thodor12 commented
Ray suggested a vertical check if `xz` matches the building `xz` exactly, thoughts?

2022-05-15 17:39 UTC, MotionlessTrain commented
That may work, but there is still the edge case that both x, y and z are equal

2022-05-15 17:39 UTC, Thodor12 commented
> That may work, but there is still the edge case that both x, y and z are equal

If that ever occurs I'm just going to return a sarcastic message, "how the hell did you manage that?"

2022-05-15 17:41 UTC, Raycoms commented
> That may work, but there is still the edge case that both x, y and z are equal

Not possible, the hut block is there =D

2022-05-15 17:52 UTC, Raycoms commented on src/api/java/com/minecolonies/api/util/BlockPosUtil.java
> +        return component.orElse(new TranslationTextComponent(DIRECTION_NONE));
Oh no, don't package this through an optional. null checks are fine, no need to create wrappers everywhere

2022-05-15 17:52 UTC, Raycoms commented on src/api/java/com/minecolonies/api/util/BlockPosUtil.java
> +        return component.orElse(new TranslationTextComponent(DIRECTION_NONE));
can always component == null ? NONE : component;

2022-05-15 17:53 UTC, MotionlessTrain commented
> > That may work, but there is still the edge case that both x, y and z are equal
> 
> Not possible, the hut block is there =D

I agree, in that case the function was called wrongly, so that is more a problem at the call side :D

2022-05-15 17:55 UTC, Thodor12 commented
> > > That may work, but there is still the edge case that both x, y and z are equal
> > 
> > 
> > Not possible, the hut block is there =D
> 
> I agree, in that case the function was called wrongly, so that is more a problem at the call side :D

I'm returning a text now just in case it happens, at least you don't get an outright crash, which is always better.

2022-05-15 17:58 UTC, Nightenom approved these changes, later dismissed

2022-05-15 18:01 UTC, Raycoms submitted a review, later dismissed

2022-05-15 20:14 UTC, OrionDevelopment requested changes
This looks to me like an untested not required change.

Please list the issue number this relates to, describe your changes better and add comments in the code why the check needs to be this way.

2022-05-15 20:15 UTC, Thodor12 commented
I have tested this and I've commented in the other issue towards this with the related problem

2022-05-15 20:15 UTC, OrionDevelopment commented
If this is referenced somewhere else, then please state so in the pr description, on the phone i can not see those directly.

Additional code comments are for sure required though

2022-05-15 20:21 UTC, Thodor12 commented
> If this is referenced somewhere else, then please state so in the pr description, on the phone i can not see those directly.
> 
> Additional code comments are for sure required though

I updated the PR description since the changes updated a bit since PR creation, code comments shouldn't be necessary though as the code is pretty straightforward

2022-05-15 20:45 UTC, OrionDevelopment commented
Code comments are needed since this pr changes a rather complicated if switch. Please document properly as to why this change is needed in the code.

This is not much work, it takes 10 seconds to do, but Dave's others who are reading that code during debugging sessions from having to look it up here, if they can even easily find it.

2022-05-15 20:49 UTC, OrionDevelopment commented
Additionally your pr description is still not very good. The four bullet points don't describe what you are actually doing to what method and why.

Please elaborate your reasoning as to why you think those four points are sufficient.

2022-05-15 21:08 UTC, Thodor12 commented
@OrionDevelopment I updated the description again, is it good enough now?

2022-05-16 06:35 UTC, OrionDevelopment approved these changes

2022-05-16 06:36 UTC, merged