Dynmap compatability
ldtteam/minecolonies pull request #8784
Opened 2022-11-24 12:06 UTC by Thodor12

Closes ldtteam/minecolonies-features#728

# Changes proposed in this pull request:
- Ability to render borders of colonies on Dynmap using a new marker set "Colonies".
- Renders the colony name, owner and population count on the description of the colony.
- Automatically updates Dynmap when the following occur:
  - The colony name gets changed
  - The colony it's team color is changed
  - The colony borders change when a building is constructured/repaired/removed
  - The colony it's population count changes, either when colonists are born or die.

What is not added in the pull request:
- Ability for Minecolonies specific blocks (primarly hut blocks) to render on Dynmap
- Ability for DO blocks to render on Dynmap (this would have to be implemented from within DO, should not appear here)

Review please

2022-12-12 23:41 UTC, IceGoalie31 commented
Thank you so much

2022-12-13 19:21 UTC, Raycoms commented on src/api/java/com/minecolonies/api/compatibility/dynmap/ColonyChunkClaimCalculator.java
> +public class ColonyChunkClaimCalculator
javadoc on classes and public methods

2022-12-13 19:21 UTC, Raycoms commented on src/api/java/com/minecolonies/api/compatibility/dynmap/ColonyChunkClaimCalculator.java
> +        var protectionAreaCenterChunk = new ChunkPos(colony.getCenter());
Please avoid var if possible

2022-12-13 19:23 UTC, Raycoms commented on src/api/java/com/minecolonies/api/compatibility/dynmap/Constants.java
> +public final class Constants
Id call the class DynmapConstants + javadoc

2022-12-13 19:23 UTC, Raycoms commented on src/api/java/com/minecolonies/api/compatibility/dynmap/DynmapApiListener.java
> +public class DynmapApiListener extends DynmapCommonAPIListener
javadoc on public methods and classes

2022-12-13 19:23 UTC, Raycoms commented on src/api/java/com/minecolonies/api/compatibility/dynmap/DynmapCompat.java
> +public class DynmapCompat extends DynmapProxy
jdoc

2022-12-13 19:24 UTC, Raycoms commented on src/api/java/com/minecolonies/api/compatibility/dynmap/DynmapIntegration.java
> +public class DynmapIntegration
jdoc on class and public methods

2022-12-13 19:24 UTC, Raycoms commented on src/api/java/com/minecolonies/api/compatibility/dynmap/DynmapIntegration.java
> +        var colonySetInternal = markerApi.getMarkerSet(DYNMAP_COLONY_MARKER_SET_ID);
Also please less var

2022-12-13 19:25 UTC, Raycoms commented on src/api/java/com/minecolonies/api/compatibility/Compatibility.java
> +     * Update the colony team color
Jdoc should probably be "Called on updating the colony team color"

2022-12-13 19:26 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/network/messages/server/colony/ColonyDeleteOwnMessage.java
> +            if (isLogicalServer) {
brackets, also applies to the next

2022-12-13 19:27 UTC, Raycoms requested changes
Implementation wise is looks okay, style wise it needs some cleanup

2022-12-21 10:29 UTC, someaddons commented
Did you try loading minecolonies without dynmap present yet?

2022-12-22 08:15 UTC, Thodor12 commented
> Did you try loading minecolonies without dynmap present yet?

Yes, this works just fine

2022-12-22 10:56 UTC, someaddons approved these changes

2022-12-22 10:57 UTC, merged