Fix/crashes expceptions
ldtteam/minecolonies pull request #954
Opened 2017-05-08 23:20 UTC by Raycoms

Closes #953

# Changes proposed in this pull request:
- Fixes a nullpointer exception with citizenData

Review please

2017-05-08 23:31 UTC, MinecoloniesSonar commented
SonarQube analysis reported 113 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 44 major
* ![MINOR][MINOR] 58 minor
* ![INFO][INFO] 10 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.289 lines, which is greater than 750 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 64 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L356](https://github.com/Minecolonies/minecolonies/blob/5b31f1744521cfe5c7dae53c65014357dd46da3e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L356): Assign this magic number 6.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-08 23:40 UTC, MinecoloniesSonar commented
SonarQube analysis reported 114 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 45 major
* ![MINOR][MINOR] 58 minor
* ![INFO][INFO] 10 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.289 lines, which is greater than 750 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 64 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/e8a9030392496ac475ddde16635b95a27a925321/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-09 01:32 UTC, MinecoloniesSonar commented
SonarQube analysis reported 114 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 45 major
* ![MINOR][MINOR] 58 minor
* ![INFO][INFO] 10 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.289 lines, which is greater than 750 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 64 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/d8fd0478fda116993d614e3a0bf70018ab0ca852/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-09 06:21 UTC, marvin-bitterlich requested changes
You killed the creative tab background? What happened there?

2017-05-09 06:21 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/colony/CitizenData.java
> +                citizenName = generateName(rand);
This will stackoverflow if all names are used.

2017-05-09 12:11 UTC, MinecoloniesSonar commented
SonarQube analysis reported 114 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 45 major
* ![MINOR][MINOR] 58 minor
* ![INFO][INFO] 10 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.289 lines, which is greater than 750 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 64 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/ab344661f2ee1c9f99049414ad5cdb290c231ad9/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-09 12:21 UTC, MinecoloniesSonar commented
SonarQube analysis reported 118 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 46 major
* ![MINOR][MINOR] 58 minor
* ![INFO][INFO] 13 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.289 lines, which is greater than 750 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 64 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/b2d60aec20d073684efec12718a366602e7afe46/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-09 13:05 UTC, MinecoloniesSonar commented
SonarQube analysis reported 118 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 46 major
* ![MINOR][MINOR] 58 minor
* ![INFO][INFO] 13 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BlockUtils.java#L238](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L238): Reduce the number of conditional operators (6) used in the expression (maximum allowed 5). [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1067)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.289 lines, which is greater than 750 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 64 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/304e319ebf6a1099f393460836245c63a6c2d4d2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-09 13:27 UTC, Raycoms commented on src/main/java/com/minecolonies/coremod/colony/CitizenData.java
> +                citizenName = generateName(rand);
Nojo created that a whole while ago already.
That's the same like in 1.10 I just copied it from there to here because merged broke it

2017-05-09 14:14 UTC, merged