1.11 d-man delivery fix
ldtteam/minecolonies pull request #980
Opened 2017-05-12 08:44 UTC by xavierh

When the worker chest is full, the dman take on stack but the item he deliver disappear.
 
# Changes proposed in this pull request:
- Fix incorrect javadoc
- forceTransferStack return the stack when it can not transfer

WIP

2017-05-12 08:48 UTC, marchermans requested changes
Javadoc is still not correct.

2017-05-12 08:48 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/util/InventoryUtils.java
> +     * @return Empty when successful, otherwise return the itemStack which was supposed to be added.
This is not correct.
It Returns the stack it replaced. Which might be the original stack if nothing is replaced, however this is not guaranteed.

2017-05-12 08:48 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/util/InventoryUtils.java
> +     * @return Empty if successfull, otherwise the itemStask which was supposed to be added.
See above.

2017-05-12 08:52 UTC, xavierh commented on src/main/java/com/minecolonies/coremod/util/InventoryUtils.java
> +     * @return Empty when successful, otherwise return the itemStack which was supposed to be added.
So it is empty when it has been transfered without swapping,
otherwise when not empty:
It return the itemStack it hase been swapped with
or
return the itemstack it cold not transfer.
Correct ?
Can it transfer partial stack ?

2017-05-12 08:52 UTC, MinecoloniesSonar commented
SonarQube analysis reported 84 issues
* ![MAJOR][MAJOR] 30 major
* ![MINOR][MINOR] 48 minor
* ![INFO][INFO] 6 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L38](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L38): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 32 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L38](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L38): class "AbstractBuilding" has 68 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L106](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L106): Remove this reference to "BuildingBaker". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L106](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L106): Remove this reference to "BuildingBaker". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L107](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L107): Remove this reference to "BuildingBlacksmith". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L107](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L107): Remove this reference to "BuildingBlacksmith". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L108](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L108): Remove this reference to "BuildingBuilder". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L109](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L109): Remove this reference to "BuildingHome". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L109](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L109): Remove this reference to "BuildingHome". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L110](https://github.com/Minecolonies/minecolonies/blob/1badc34aebf24aa76ac27fea0c6ac0fbdf90c351/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L110): Remove this reference to "BuildingFarmer". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-12 08:53 UTC, OrionDevelopment commented on src/main/java/com/minecolonies/coremod/util/InventoryUtils.java
> +     * @return Empty when successful, otherwise return the itemStack which was supposed to be added.
Yes it can Transfer a partial stack. It will try partial first before swapping.

2017-05-12 09:21 UTC, MinecoloniesSonar commented
SonarQube analysis reported 84 issues
* ![MAJOR][MAJOR] 30 major
* ![MINOR][MINOR] 48 minor
* ![INFO][INFO] 6 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L38](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L38): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 32 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L38](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L38): class "AbstractBuilding" has 68 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L106](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L106): Remove this reference to "BuildingBaker". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L106](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L106): Remove this reference to "BuildingBaker". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L107](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L107): Remove this reference to "BuildingBlacksmith". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L107](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L107): Remove this reference to "BuildingBlacksmith". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L108](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L108): Remove this reference to "BuildingBuilder". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L109](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L109): Remove this reference to "BuildingHome". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L109](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L109): Remove this reference to "BuildingHome". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L110](https://github.com/Minecolonies/minecolonies/blob/2ffefde701bdc042fbb7536a53f9fb3e201b69d0/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L110): Remove this reference to "BuildingFarmer". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-12 12:26 UTC, marchermans reviewed
The JavaDoc is now correct.

2017-05-12 12:26 UTC, marchermans approved these changes

2017-05-12 15:34 UTC, Kostronor commented
:shipit: @Raycoms

2017-05-12 15:36 UTC, xavierh commented
@Kostronor Don't merge, I am not done with it

2017-05-12 15:44 UTC, MinecoloniesSonar commented
SonarQube analysis reported 100 issues
* ![MAJOR][MAJOR] 44 major
* ![MINOR][MINOR] 49 minor
* ![INFO][INFO] 7 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.203 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 42 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): class "Colony" has 81 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): Refactor this class so it has no more than 20 fields, rather than the 35 it currently has. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [Colony.java#L172](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L172): Assign this magic number 5 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L547](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L547): Reduce the number of returns of this method 11, down to the maximum allowed 6. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1007](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1007): Assign this magic number 20 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1008](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1008): Assign this magic number 60 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1132](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1132): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1134](https://github.com/Minecolonies/minecolonies/blob/1dc187294f5a2140ddcf519cfff16dc97dc236d2/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1134): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-12 18:47 UTC, MinecoloniesSonar commented
SonarQube analysis reported 100 issues
* ![MAJOR][MAJOR] 44 major
* ![MINOR][MINOR] 49 minor
* ![INFO][INFO] 7 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.203 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 42 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): class "Colony" has 81 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L44](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L44): Refactor this class so it has no more than 20 fields, rather than the 35 it currently has. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [Colony.java#L172](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L172): Assign this magic number 5 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L547](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L547): Reduce the number of returns of this method 11, down to the maximum allowed 6. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1007](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1007): Assign this magic number 20 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1008](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1008): Assign this magic number 60 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1132](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1132): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1134](https://github.com/Minecolonies/minecolonies/blob/ee9828d33f0a4cff4fd9be8d5d664b20b2bf0561/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1134): Assign this magic number 16 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-12 18:50 UTC, Raycoms commented
:shipit:

2017-05-12 19:17 UTC, Raycoms commented
:shipit:  Nice that one will bring stability to 1.11.2 finally I feel.

2017-05-13 10:07 UTC, Kostronor commented
:shipit:

2017-05-13 10:08 UTC, merged

2017-05-13 10:10 UTC, xavierh commented
This could have been an hotfix. I don't know when the next release is.
I will do the back port for 1.10 sometimes this week end

On 13 May 2017 11:08, "Marvin Hofmann" <notifications@github.com> wrote:

> Merged #980 <https://github.com/Minecolonies/minecolonies/pull/980>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Minecolonies/minecolonies/pull/980#event-1080945910>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ACplvMq_i9Adg0T6mx_J4iKqRXVEkPsOks5r5YEYgaJpZM4NZAPF>
> .
>