Polymorph-like support for teaching crafting
ldtteam/minecolonies pull request #9907
Opened 2024-04-11 13:08 UTC by uecasm

Closes ldtteam/minecolonies-features#808

# Changes proposed in this pull request:
- Adds a button to the crafting teaching window to switch output items if there are conflicting recipes.
    - Pictured: added a couple of extra recipes for crafting planks via datapack (as an example; recipes not included):
        ![craftingswitch](https://github.com/ldtteam/minecolonies/assets/539951/78ea0ad4-92e9-4f92-844b-e09f63745cc9)
    - This is similar to functionality in the Polymorph mod, but does not require that.
    - Only implemented for the crafting grid teaching; it doesn't work for furnace recipe conflicts, those are more complex.

[x] Yes I tested this before submitting it.
[x] I also did a multiplayer test.

Review please (could port)

2024-04-11 14:01 UTC, Raycoms submitted a review, later dismissed

2024-04-12 20:25 UTC, Sandriell commented on src/main/resources/assets/minecolonies/textures/gui/craftingswitch.png
Any reason why this is 256x256 when it only needs to be 32x64 ?

Or ideally, 16x32. I threw together a quick button set at that size, if interested.

![craftingswitch2](https://github.com/ldtteam/minecolonies/assets/10704907/e4d491a7-dd48-4661-97f5-b47589116b47)

Similar to Polymorph's style (without being a copy) for consistency and what end users would be used to.

2024-04-12 20:41 UTC, Thodor12 commented on src/main/resources/assets/minecolonies/textures/gui/craftingswitch.png
When you want to render images on a GUI, you have to use something called a blit, essentially capturing part of an image and drawing it on the screen. By default the blit assumes the texture size is 256x256.

2024-04-12 22:37 UTC, uecasm commented on src/main/resources/assets/minecolonies/textures/gui/craftingswitch.png
Yeah, it's possible to use textures with different sizes, but 256x256 is sort of the standard tile that it defaults to.

Thanks for the images, though; it was somewhat deliberate to use something not identical to Polymorph, but you're right that something closer would probably be more familiar to people.  I didn't use your image as-is but I've incorporated it into mine.

2024-04-13 06:46 UTC, Nightenom requested changes
Don't create new atlases by manual stitching, 1.20.4+ would require unstitcher definition...

2024-04-13 07:01 UTC, uecasm commented
I don't know what that even means.  It's just using a standard GUI control class.

2024-04-13 07:14 UTC, Nightenom commented on src/main/resources/assets/minecolonies/textures/gui/craftingswitch.png
Sorry, was on mobile, but I meant this, go with two images, cuz anything that goes into vanilla ui or our ImageButton in 1.20.4+ must have either unstitcher definition in atlas JSON (see vanilla wiki) or be split into two images

2024-04-13 07:22 UTC, uecasm commented on src/main/resources/assets/minecolonies/textures/gui/craftingswitch.png
In 1.20.1 it won't work unless both images are in a single texture.  That's just how the vanilla `ImageButton` works.  It could be split in 1.20.4 if that's different.

2024-04-14 14:05 UTC, someaddons approved these changes

2024-04-14 14:09 UTC, merged