Feature/1.11 better chat
ldtteam/minecolonies pull request #994
Opened 2017-05-15 13:17 UTC by xavierh

# Changes proposed in this pull request:
- d-man say which chest is full and only when he could not swap items
- builder say when they start/finish a job
- Colony name in chat only displayed, when not the players own colony
- d-man hold the item he gather or deliver in his hand
- remove some warnings

WIP

2017-05-15 13:24 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java
> +                            if (workerBuilding != null && workerBuilding.getWorker() != null)
![CRITICAL](https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL') Refactor this code to not nest more than 5 if/for/while/switch/try statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS134)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove this expression which always evaluates to "true" [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2589)

2017-05-15 13:24 UTC, MinecoloniesSonar commented
SonarQube analysis reported 68 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 22 major
* ![MINOR][MINOR] 42 minor
* ![INFO][INFO] 3 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/8b0587fea3cf685faa08f08a15647dcbf474d6a2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.297 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/8b0587fea3cf685faa08f08a15647dcbf474d6a2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 64 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/8b0587fea3cf685faa08f08a15647dcbf474d6a2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L66](https://github.com/Minecolonies/minecolonies/blob/8b0587fea3cf685faa08f08a15647dcbf474d6a2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L66): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/8b0587fea3cf685faa08f08a15647dcbf474d6a2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/8b0587fea3cf685faa08f08a15647dcbf474d6a2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/8b0587fea3cf685faa08f08a15647dcbf474d6a2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/8b0587fea3cf685faa08f08a15647dcbf474d6a2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L356](https://github.com/Minecolonies/minecolonies/blob/8b0587fea3cf685faa08f08a15647dcbf474d6a2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L356): Assign this magic number 6.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L385](https://github.com/Minecolonies/minecolonies/blob/8b0587fea3cf685faa08f08a15647dcbf474d6a2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L385): Assign this magic number 3 to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-15 14:03 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java
> +       resetFields();
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Make this line start at column 9. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-05-15 14:03 UTC, MinecoloniesSonar commented
SonarQube analysis reported 74 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 25 major
* ![MINOR][MINOR] 43 minor
* ![INFO][INFO] 4 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BuildingFarmer.java#L303](https://github.com/Minecolonies/minecolonies/blob/491221eec369976187c0667a312de2b8eb2c436f/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L303): Define a constant instead of duplicating this literal "com.minecolonies.coremod.gui.scarecrow.user" 3 times. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1192)
1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L108](https://github.com/Minecolonies/minecolonies/blob/491221eec369976187c0667a312de2b8eb2c436f/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L108): Remove this unused method parameter "stack". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L264](https://github.com/Minecolonies/minecolonies/blob/491221eec369976187c0667a312de2b8eb2c436f/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L264): Reduce this class from 32 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingFarmer.java#L497](https://github.com/Minecolonies/minecolonies/blob/491221eec369976187c0667a312de2b8eb2c436f/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L497): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/491221eec369976187c0667a312de2b8eb2c436f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.293 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L65](https://github.com/Minecolonies/minecolonies/blob/491221eec369976187c0667a312de2b8eb2c436f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L65): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 63 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L65](https://github.com/Minecolonies/minecolonies/blob/491221eec369976187c0667a312de2b8eb2c436f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L65): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L65](https://github.com/Minecolonies/minecolonies/blob/491221eec369976187c0667a312de2b8eb2c436f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L65): Refactor this class so it has no more than 20 fields, rather than the 21 it currently has. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/491221eec369976187c0667a312de2b8eb2c436f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/491221eec369976187c0667a312de2b8eb2c436f/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-15 15:26 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java
> +    @Override
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Make this line start at column 9. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AIndentationCheck)

2017-05-15 15:26 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java
> +                            if (workerBuilding.getWorker() != null)
![CRITICAL](https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL') Refactor this code to not nest more than 5 if/for/while/switch/try statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS134)
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Remove this expression which always evaluates to "true" [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2589)

2017-05-15 15:26 UTC, MinecoloniesSonar commented
SonarQube analysis reported 85 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 32 major
* ![MINOR][MINOR] 45 minor
* ![INFO][INFO] 5 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [BuildingFarmer.java#L303](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L303): Define a constant instead of duplicating this literal "com.minecolonies.coremod.gui.scarecrow.user" 3 times. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [AbstractJob.java#L337](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L337): Remove usage of generic wildcard type. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L108](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L108): Remove this unused method parameter "stack". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L264](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L264): Reduce this class from 32 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingFarmer.java#L497](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L497): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [AbstractJob.java#L52](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L52): Remove this reference to "JobPlaceholder". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L53](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L53): Remove this reference to "JobBuilder". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L54](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L54): Remove this reference to "JobDeliveryman". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L55](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L55): Remove this reference to "JobMiner". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractJob.java#L56](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/colony/jobs/AbstractJob.java#L56): Remove this reference to "JobLumberjack". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-15 15:36 UTC, MinecoloniesSonar commented
SonarQube analysis reported 72 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 23 major
* ![MINOR][MINOR] 43 minor
* ![INFO][INFO] 5 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L108](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L108): Remove this unused method parameter "stack". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L264](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L264): Reduce this class from 32 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingFarmer.java#L500](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L500): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.270 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 58 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L351](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L351): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/f12bd82dea86dc14f8d7680e65daf3830e60c99e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-15 17:08 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java
> +                            if (buildingToDeliver instanceof AbstractBuildingWorker)
![CRITICAL](https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL') Refactor this code to not nest more than 5 if/for/while/switch/try statements. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS134)

2017-05-15 17:08 UTC, MinecoloniesSonar commented
SonarQube analysis reported 72 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 23 major
* ![MINOR][MINOR] 43 minor
* ![INFO][INFO] 5 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L108](https://github.com/Minecolonies/minecolonies/blob/532e80c46e902996b0f36cbdfc5a9c17c596e1d1/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L108): Remove this unused method parameter "stack". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L264](https://github.com/Minecolonies/minecolonies/blob/532e80c46e902996b0f36cbdfc5a9c17c596e1d1/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L264): Reduce this class from 32 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingFarmer.java#L499](https://github.com/Minecolonies/minecolonies/blob/532e80c46e902996b0f36cbdfc5a9c17c596e1d1/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L499): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/532e80c46e902996b0f36cbdfc5a9c17c596e1d1/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.270 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/532e80c46e902996b0f36cbdfc5a9c17c596e1d1/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 58 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/532e80c46e902996b0f36cbdfc5a9c17c596e1d1/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L351](https://github.com/Minecolonies/minecolonies/blob/532e80c46e902996b0f36cbdfc5a9c17c596e1d1/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L351): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/532e80c46e902996b0f36cbdfc5a9c17c596e1d1/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/532e80c46e902996b0f36cbdfc5a9c17c596e1d1/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/532e80c46e902996b0f36cbdfc5a9c17c596e1d1/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-15 18:59 UTC, MinecoloniesSonar commented
SonarQube analysis reported 72 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 23 major
* ![MINOR][MINOR] 43 minor
* ![INFO][INFO] 5 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L108](https://github.com/Minecolonies/minecolonies/blob/d07d71c5b52bb7a5e20710c3765df7616afb1b52/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L108): Remove this unused method parameter "stack". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L264](https://github.com/Minecolonies/minecolonies/blob/d07d71c5b52bb7a5e20710c3765df7616afb1b52/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L264): Reduce this class from 32 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingFarmer.java#L499](https://github.com/Minecolonies/minecolonies/blob/d07d71c5b52bb7a5e20710c3765df7616afb1b52/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L499): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/d07d71c5b52bb7a5e20710c3765df7616afb1b52/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1,270 lines, which is greater than 1,000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/d07d71c5b52bb7a5e20710c3765df7616afb1b52/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 58 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/d07d71c5b52bb7a5e20710c3765df7616afb1b52/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L351](https://github.com/Minecolonies/minecolonies/blob/d07d71c5b52bb7a5e20710c3765df7616afb1b52/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L351): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/d07d71c5b52bb7a5e20710c3765df7616afb1b52/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/d07d71c5b52bb7a5e20710c3765df7616afb1b52/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/d07d71c5b52bb7a5e20710c3765df7616afb1b52/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-15 22:37 UTC, MinecoloniesSonar commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java
> +import com.minecolonies.coremod.util.Log;
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Remove this unused import 'com.minecolonies.coremod.util.Log'. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AUselessImportCheck)

2017-05-15 22:37 UTC, MinecoloniesSonar commented
SonarQube analysis reported 73 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 23 major
* ![MINOR][MINOR] 44 minor
* ![INFO][INFO] 5 info

Watch the comments in this conversation to review them.

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L108](https://github.com/Minecolonies/minecolonies/blob/16de9b09b5c0be96da7b81f3e18016ccd62b36f6/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L108): Remove this unused method parameter "stack". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L264](https://github.com/Minecolonies/minecolonies/blob/16de9b09b5c0be96da7b81f3e18016ccd62b36f6/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L264): Reduce this class from 32 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingFarmer.java#L499](https://github.com/Minecolonies/minecolonies/blob/16de9b09b5c0be96da7b81f3e18016ccd62b36f6/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L499): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/16de9b09b5c0be96da7b81f3e18016ccd62b36f6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.273 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/16de9b09b5c0be96da7b81f3e18016ccd62b36f6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 58 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/16de9b09b5c0be96da7b81f3e18016ccd62b36f6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L351](https://github.com/Minecolonies/minecolonies/blob/16de9b09b5c0be96da7b81f3e18016ccd62b36f6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L351): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/16de9b09b5c0be96da7b81f3e18016ccd62b36f6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/16de9b09b5c0be96da7b81f3e18016ccd62b36f6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/16de9b09b5c0be96da7b81f3e18016ccd62b36f6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-15 22:50 UTC, MinecoloniesSonar commented
SonarQube analysis reported 71 issues
* ![MAJOR][MAJOR] 22 major
* ![MINOR][MINOR] 44 minor
* ![INFO][INFO] 5 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L108](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L108): Remove this unused method parameter "stack". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L264](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L264): Reduce this class from 32 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingFarmer.java#L499](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L499): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.273 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 58 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L351](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L351): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-15 22:56 UTC, MinecoloniesSonar commented
SonarQube analysis reported 70 issues
* ![MAJOR][MAJOR] 22 major
* ![MINOR][MINOR] 43 minor
* ![INFO][INFO] 5 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L108](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L108): Remove this unused method parameter "stack". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L264](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L264): Reduce this class from 32 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingFarmer.java#L499](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L499): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.273 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 58 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L351](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L351): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/30c1eafb3f62ccf14ed999fd43e5439ae42cbdb6/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-16 07:20 UTC, marvin-bitterlich requested changes
looking good! Just some small things

2017-05-16 07:20 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/colony/jobs/JobFisherman.java
> +            this.getColony().triggerAchievement(ModAchievements.achievementFisherDeathGuardian);
nice :+1:

2017-05-16 07:20 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/colony/jobs/JobGuard.java
> +            citizen.getColony().triggerAchievement(ModAchievements.achievementGuardDeathEnderman);
awesome :+1:

2017-05-16 07:20 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java
> +        job.triggerDeathAchievement(source, this);
nice cleanup!

2017-05-16 07:20 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java
> +        players.remove(owner);
you should always copy the list explicitly if you modify it

2017-05-16 07:20 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java
> +                      InventoryUtils.swapToolGrade(hutLevel));
just noticed this, can we rename this? It is really unclear atm…

2017-05-16 07:20 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java
> +                worker.sendLocalizedChat("entity.builder.messageBuildStart", wo.getName());
can we move this to my new translation constants?

2017-05-16 07:20 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java
> +        final AbstractBuilding buildingToDeliver = ((BuildingDeliveryman) ownBuilding).getBuildingToDeliver();
this will break if the cast fails

2017-05-16 07:20 UTC, Kostronor commented on src/main/java/com/minecolonies/coremod/entity/ai/citizen/deliveryman/EntityAIWorkDeliveryman.java
> +                        chatSpamFilter.talkWithoutSpam("com.minecolonies.coremod.job.deliveryman.workerChestFull",
constants here too please :smile:

2017-05-16 07:54 UTC, xavierh commented on src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java
> +                      InventoryUtils.swapToolGrade(hutLevel));
@Kostronor any suggestion ?

2017-05-16 09:54 UTC, MinecoloniesSonar commented
SonarQube analysis reported 71 issues
* ![MAJOR][MAJOR] 22 major
* ![MINOR][MINOR] 44 minor
* ![INFO][INFO] 5 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L108](https://github.com/Minecolonies/minecolonies/blob/dd338562ca62ca78dd1e298f9f2a9602bf3417aa/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L108): Remove this unused method parameter "stack". [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L264](https://github.com/Minecolonies/minecolonies/blob/dd338562ca62ca78dd1e298f9f2a9602bf3417aa/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L264): Reduce this class from 32 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingFarmer.java#L499](https://github.com/Minecolonies/minecolonies/blob/dd338562ca62ca78dd1e298f9f2a9602bf3417aa/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L499): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/dd338562ca62ca78dd1e298f9f2a9602bf3417aa/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.273 lines, which is greater than 1.000 authorized. Split it into smaller files. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/dd338562ca62ca78dd1e298f9f2a9602bf3417aa/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 58 to the maximum authorized 30 or less. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/dd338562ca62ca78dd1e298f9f2a9602bf3417aa/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L351](https://github.com/Minecolonies/minecolonies/blob/dd338562ca62ca78dd1e298f9f2a9602bf3417aa/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L351): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/dd338562ca62ca78dd1e298f9f2a9602bf3417aa/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/dd338562ca62ca78dd1e298f9f2a9602bf3417aa/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/dd338562ca62ca78dd1e298f9f2a9602bf3417aa/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2017-05-16 11:58 UTC, marvin-bitterlich approved these changes

2017-05-16 12:03 UTC, Raycoms commented
:shipit:

2017-05-16 12:06 UTC, merged