Message fixes
ldtteam/minecolonies pull request #9945
Opened 2024-05-08 20:06 UTC by someaddons

# Changes proposed in this pull request:
- Fix Visitors food interaction response being sent to all players
- Removed old citizen message handler in favor of utils

[ ] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please

2024-05-09 20:51 UTC, Thodor12 requested changes

2024-05-09 20:51 UTC, Thodor12 commented on src/main/java/com/minecolonies/core/colony/jobs/JobDeliveryman.java
> +            getCitizen().getEntity().ifPresent(e -> MessageUtils.forCitizen(e, COM_MINECOLONIES_COREMOD_ENTITY_DELIVERYMAN_FORCEPICKUP));
You still need a `sendTo()` after `forCitizen`, since that method only returns a message builder, you need to call the finalizer to actually send the message

2024-05-09 20:51 UTC, Thodor12 commented on src/main/java/com/minecolonies/core/entity/ai/workers/AbstractEntityAIStructureWithWorkOrder.java
> +                MessageUtils.forCitizen(worker, COM_MINECOLONIES_COREMOD_ENTITY_BUILDER_BUILD_START, job.getWorkOrder().getDisplayName());
Same as above

2024-05-09 20:51 UTC, Thodor12 commented on src/main/java/com/minecolonies/core/entity/ai/workers/AbstractEntityAIStructureWithWorkOrder.java
> +                MessageUtils.forCitizen(worker, COM_MINECOLONIES_COREMOD_ENTITY_BUILDER_BUILD_START, job.getWorkOrder().getDisplayName());
Same as above

2024-05-09 20:51 UTC, Thodor12 commented on src/main/java/com/minecolonies/core/entity/ai/workers/builder/EntityAIStructureBuilder.java
> +        MessageUtils.forCitizen(worker, message);
Same as above

2024-05-09 20:51 UTC, Thodor12 commented on src/main/java/com/minecolonies/core/entity/ai/workers/service/EntityAIWorkUndertaker.java
> +            MessageUtils.forCitizen(worker, Component.translatable(MESSAGE_INFO_CITIZEN_UNDERTAKER_GRAVEYARD_NO_SPACE, module.getLastGraveData().getCitizenName()));
Same as above

2024-05-10 11:59 UTC, someaddons commented on src/main/java/com/minecolonies/core/colony/jobs/JobDeliveryman.java
> +            getCitizen().getEntity().ifPresent(e -> MessageUtils.forCitizen(e, COM_MINECOLONIES_COREMOD_ENTITY_DELIVERYMAN_FORCEPICKUP));
ye good catch, fixed^^

2024-05-10 12:02 UTC, Raycoms approved these changes

2024-05-10 16:01 UTC, marchermans approved these changes

2024-05-10 16:52 UTC, Thodor12 approved these changes

2024-05-12 06:58 UTC, merged